package TestPrep;

/**
 * Created by hfletcher on 19/06/2018.
 */
public class AllLeadProvidersTwo {

    public static String[][] AllLeadProviders = new String[][]{
            {"Apply Online", "New"},
            {"Apply Online Sat", "New"},
            {"Apply Online Sun", "New"},
            {"Apply Online INCOMPLETE", "New"},
            {"Apply Online INCOMPLETE Sat", "New"},
            {"Apply Online INCOMPLETE Sun", "New"},
            {"Aspect Webmedia", "New"},
            {"Aspect Webmedia Sat", "New"},
            {"Aspect Webmedia Sun", "New"},
            {"Best Health Policy RA", "New"},
            {"Best Health Policy RA Sat", "New"},
            {"Best Health Policy RA Sun", "New"},
            {"Cavendish", "New"},
            {"Cavendish Dec", "New"},
            {"Cavendish Dec - DNC", "New"},
            {"Cavendish Dec - Hotkey", "New"},
            {"Cavendish - DNC", "New"},
            {"Cavendish Dec Customer Referral", "New"},
            {"Cavendish - Hotkey", "New"},
            {"Cavendish Customer Referral", "New"},
            {"clixel", "New"},
            {"CompareLife", "New"},
            {"clixel RA", "New"},
            {"Conectia", "New"},
            {"Deal Direct FS", "New"},
            {"DST Team", "New"},
            {"Dove Insurance", "New"},
            {"e-Finity", "New"},
            {"Engaged Solutions", "New"},
            {"eHealthCompare RA", "New"},
            {"eHealthCompare RA Sat", "New"},
            {"eHealthCompare RA Sun", "New"},
            {"eprospects", "New"},
            {"eprospect SAT", "New"},
            {"eprospect SUN", "New"},
            {"Esmart", "New"},
            {"Esmart Sat", "New"},
            {"Esmart Sun", "New"},
            {"finance_leads_online", "New"},
            {"50PlusLife.co.uk", "New"},
            {"Google", "New"},
            {"Hotkey(Internal)", "New"},
            {"HotKey Lead", "New"},
            {"Hotkey(Cavendish)", "New"},
            {"Hotkey(SunLife FLI)", "New"},
            {"Hotkey(SunLife GOF)", "New"},
            {"Impressia", "New"},
            {"internal", "New"},
            {"Kamicom", "New"},
            {"leadbay", "New"},
            {"LeadStream", "New"},
            {"LeadStream Sat", "New"},
            {"LeadStream Sun", "New"},
            {"Look For Health RA", "New"},
            {"Look For Health RA Sat", "New"},
            {"Look For Health RA Sun", "New"},
            {"look_for_life", "New"},
            {"Look For Life RA", "New"},
            {"Look For Life RA SAT", "New"},
            {"Look For Life RA SUN", "New"},
            {"LOANS REFERRAL", "New"},
            {"leadstream", "New"},
            {"leadstream Sat", "New"},
            {"leadstream Sun", "New"},
            {"livesure", "New"},
            {"Livesure RA", "New"},
            {"Livesure RA SAT", "New"},
            {"Livesure RA SUN", "New"},
            {"michael_anthony", "New"},
            {"michael_anthony SAT", "New"},
            {"michael_anthony SUN", "New"},
            {"michael_anthony ADD", "New"},
            {"MA WOL", "New"},
            {"MA WOL Sat", "New"},
            {"MA WOL Sun", "New"},
            {"MA WOL ADD", "New"},
            {"MA Switch", "New"},
            {"MA Switch Sat", "New"},
            {"MA Switch Sun", "New"},
            {"michael_anthony COMM", "New"},
            {"michael_anthony COMM SAT", "New"},
            {"michael_anthony COMM SUN", "New"},
            {"Baby Hotkey", "New"},
            {"Business Leads", "New"},
            {"BTQ Hotkey", "New"},
            {"BuyLife", "New"},
            {"First to Market", "New"},
            {"MA Inbound", "New"},
            {"Niche Data", "New"},
            {"Niche Hot Key", "New"},
            {"OSL", "New"},
            {"www.protected.co.uk", "New"},
            {"re-assured.co.uk", "New"},
            {"Customer Referral", "New"},
            {"SYN", "New"},
            {"melodi", "New"},
            {"Openwork", "New"},
            {"Protect4Life", "New"},
            {"premier_leads", "New"},
            {"premier_leads Sat", "New"},
            {"premier_leads Sun", "New"},
            {"PMI Advisor Callback", "New"},
            {"PMI Advisor Callback Sat", "New"},
            {"PMI Advisor Callback Sun", "New"},
            {"PMI Advisor Full Lead", "New"},
            {"PMI Advisor Full Lead Sat", "New"},
            {"PMI Advisor Full Lead Sun", "New"},
            {"PMI Pre CRM", "New"},
            {"Polly.co.uk", "New"},
            {"Polly.co.uk Sat", "New"},
            {"Polly.co.uk Sun", "New"},
            {"Provident", "New"},
            {"Quote Me Now", "New"},
            {"QSM Incentivised", "New"},
            {"QSM NotIncentivised", "New"},
            {"Quote Searcher", "New"},
            {"Quintessential", "New"},
            {"Quintessential Sat", "New"},
            {"Quintessential Sun", "New"},
            {"Reassured Archive S", "New"},
            {"Reassured Archive J", "New"},
            {"Reassured Health", "New"},
            {"Reassured Life", "New"},
            {"RA Email SurePolicy", "New"},
            {"RA Email SurePolicy SAT", "New"},
            {"RA Email SurePolicy SUN", "New"},
            {"RA PPC SureLoan", "New"},
            {"RA PPC SureLoan Sat", "New"},
            {"RA PPC SureLoan Sun", "New"},
            {"RA PPC SurePolicy", "New"},
            {"RA PPC SurePolicy SAT", "New"},
            {"RA PPC SurePolicy SUN", "New"},
            {"PMI Referral", "New"},
            {"PMI Client", "New"},
            {"Reassured Marketing", "New"},
            {"Reassured Marketing Sat", "New"},
            {"Reassured Marketing Sun", "New"},
            {"Reassured Marketing PMI", "New"},
            {"Reassured Marketing PMI SAT", "New"},
            {"Reassured Marketing PMI SUN", "New"},
            {"Reassured Marketing PPC", "New"},
            {"RA Shared Lead", "New"},
            {"RA Website", "New"},
            {"RA Website PMI", "New"},
            {"SunLife", "New"},
            {"SunLife Mature", "New"},
            {"SunLife Declined", "New"},
            {"SunLife - 45 day Expired", "New"},
            {"Sunlife GOF Capped", "New"},
            {"Sunlife GOF Capped DNC", "New"},
            {"Sunlife GOF", "New"},
            {"Sunlife GOF DNC", "New"},
            {"Sunlife GOF Customer Referral", "New"},
            {"Sunlife GOF(FLI)", "New"},
            {"Sunlife GOF (FLI) DNC", "New"},
            {"Sunlife GOF Expired", "New"},
            {"SunLife Hotkeys", "New"},
            {"SunLife Inbound", "New"},
            {"SunLife Customer Referral", "New"},
            {"Swinton Hotkeys", "New"},
            {"Trafix Media ", "New"},
            {"VeroCover", "New"},
            {"Visionary Markets", "New"},
            {"Visionary Markets Sat", "New"},
            {"Visionary Markets Sun", "New"},
            {"Visionary Markets Social", "New"},
            {"Apply Online", "Unknown"},
            {"Apply Online Sat", "Unknown"},
            {"Apply Online Sun", "Unknown"},
            {"Apply Online INCOMPLETE", "Unknown"},
            {"Apply Online INCOMPLETE Sat", "Unknown"},
            {"Apply Online INCOMPLETE Sun", "Unknown"},
            {"Aspect Webmedia", "Unknown"},
            {"Aspect Webmedia Sat", "Unknown"},
            {"Aspect Webmedia Sun", "Unknown"},
            {"Best Health Policy RA", "Unknown"},
            {"Best Health Policy RA Sat", "Unknown"},
            {"Best Health Policy RA Sun", "Unknown"},
            {"Cavendish", "Unknown"},
            {"Cavendish Dec", "Unknown"},
            {"Cavendish Dec - DNC", "Unknown"},
            {"Cavendish Dec - Hotkey", "Unknown"},
            {"Cavendish - DNC", "Unknown"},
            {"Cavendish Dec Customer Referral", "Unknown"},
            {"Cavendish - Hotkey", "Unknown"},
            {"Cavendish Customer Referral", "Unknown"},
            {"clixel", "Unknown"},
            {"CompareLife", "Unknown"},
            {"clixel RA", "Unknown"},
            {"Conectia", "Unknown"},
            {"Deal Direct FS", "Unknown"},
            {"DST Team", "Unknown"},
            {"Dove Insurance", "Unknown"},
            {"e-Finity", "Unknown"},
            {"Engaged Solutions", "Unknown"},
            {"eHealthCompare RA", "Unknown"},
            {"eHealthCompare RA Sat", "Unknown"},
            {"eHealthCompare RA Sun", "Unknown"},
            {"eprospects", "Unknown"},
            {"eprospect SAT", "Unknown"},
            {"eprospect SUN", "Unknown"},
            {"Esmart", "Unknown"},
            {"Esmart Sat", "Unknown"},
            {"Esmart Sun", "Unknown"},
            {"finance_leads_online", "Unknown"},
            {"50PlusLife.co.uk", "Unknown"},
            {"Google", "Unknown"},
            {"Hotkey(Internal)", "Unknown"},
            {"HotKey Lead", "Unknown"},
            {"Hotkey(Cavendish)", "Unknown"},
            {"Hotkey(SunLife FLI)", "Unknown"},
            {"Hotkey(SunLife GOF)", "Unknown"},
            {"Impressia", "Unknown"},
            {"internal", "Unknown"},
            {"Kamicom", "Unknown"},
            {"leadbay", "Unknown"},
            {"LeadStream", "Unknown"},
            {"LeadStream Sat", "Unknown"},
            {"LeadStream Sun", "Unknown"},
            {"Look For Health RA", "Unknown"},
            {"Look For Health RA Sat", "Unknown"},
            {"Look For Health RA Sun", "Unknown"},
            {"look_for_life", "Unknown"},
            {"Look For Life RA", "Unknown"},
            {"Look For Life RA SAT", "Unknown"},
            {"Look For Life RA SUN", "Unknown"},
            {"LOANS REFERRAL", "Unknown"},
            {"leadstream", "Unknown"},
            {"leadstream Sat", "Unknown"},
            {"leadstream Sun", "Unknown"},
            {"livesure", "Unknown"},
            {"Livesure RA", "Unknown"},
            {"Livesure RA SAT", "Unknown"},
            {"Livesure RA SUN", "Unknown"},
            {"michael_anthony", "Unknown"},
            {"michael_anthony SAT", "Unknown"},
            {"michael_anthony SUN", "Unknown"},
            {"michael_anthony ADD", "Unknown"},
            {"MA WOL", "Unknown"},
            {"MA WOL Sat", "Unknown"},
            {"MA WOL Sun", "Unknown"},
            {"MA WOL ADD", "Unknown"},
            {"MA Switch", "Unknown"},
            {"MA Switch Sat", "Unknown"},
            {"MA Switch Sun", "Unknown"},
            {"michael_anthony COMM", "Unknown"},
            {"michael_anthony COMM SAT", "Unknown"},
            {"michael_anthony COMM SUN", "Unknown"},
            {"Baby Hotkey", "Unknown"},
            {"Business Leads", "Unknown"},
            {"BTQ Hotkey", "Unknown"},
            {"BuyLife", "Unknown"},
            {"First to Market", "Unknown"},
            {"MA Inbound", "Unknown"},
            {"Niche Data", "Unknown"},
            {"Niche Hot Key", "Unknown"},
            {"OSL", "Unknown"},
            {"www.protected.co.uk", "Unknown"},
            {"re-assured.co.uk", "Unknown"},
            {"Customer Referral", "Unknown"},
            {"SYN", "Unknown"},
            {"melodi", "Unknown"},
            {"Openwork", "Unknown"},
            {"Protect4Life", "Unknown"},
            {"premier_leads", "Unknown"},
            {"premier_leads Sat", "Unknown"},
            {"premier_leads Sun", "Unknown"},
            {"PMI Advisor Callback", "Unknown"},
            {"PMI Advisor Callback Sat", "Unknown"},
            {"PMI Advisor Callback Sun", "Unknown"},
            {"PMI Advisor Full Lead", "Unknown"},
            {"PMI Advisor Full Lead Sat", "Unknown"},
            {"PMI Advisor Full Lead Sun", "Unknown"},
            {"PMI Pre CRM", "Unknown"},
            {"Polly.co.uk", "Unknown"},
            {"Polly.co.uk Sat", "Unknown"},
            {"Polly.co.uk Sun", "Unknown"},
            {"Provident", "Unknown"},
            {"Quote Me Now", "Unknown"},
            {"QSM Incentivised", "Unknown"},
            {"QSM NotIncentivised", "Unknown"},
            {"Quote Searcher", "Unknown"},
            {"Quintessential", "Unknown"},
            {"Quintessential Sat", "Unknown"},
            {"Quintessential Sun", "Unknown"},
            {"Reassured Archive S", "Unknown"},
            {"Reassured Archive J", "Unknown"},
            {"Reassured Health", "Unknown"},
            {"Reassured Life", "Unknown"},
            {"RA Email SurePolicy", "Unknown"},
            {"RA Email SurePolicy SAT", "Unknown"},
            {"RA Email SurePolicy SUN", "Unknown"},
            {"RA PPC SureLoan", "Unknown"},
            {"RA PPC SureLoan Sat", "Unknown"},
            {"RA PPC SureLoan Sun", "Unknown"},
            {"RA PPC SurePolicy", "Unknown"},
            {"RA PPC SurePolicy SAT", "Unknown"},
            {"RA PPC SurePolicy SUN", "Unknown"},
            {"PMI Referral", "Unknown"},
            {"PMI Client", "Unknown"},
            {"Reassured Marketing", "Unknown"},
            {"Reassured Marketing Sat", "Unknown"},
            {"Reassured Marketing Sun", "Unknown"},
            {"Reassured Marketing PMI", "Unknown"},
            {"Reassured Marketing PMI SAT", "Unknown"},
            {"Reassured Marketing PMI SUN", "Unknown"},
            {"Reassured Marketing PPC", "Unknown"},
            {"RA Shared Lead", "Unknown"},
            {"RA Website", "Unknown"},
            {"RA Website PMI", "Unknown"},
            {"SunLife", "Unknown"},
            {"SunLife Mature", "Unknown"},
            {"SunLife Declined", "Unknown"},
            {"SunLife - 45 day Expired", "Unknown"},
            {"Sunlife GOF Capped", "Unknown"},
            {"Sunlife GOF Capped DNC", "Unknown"},
            {"Sunlife GOF", "Unknown"},
            {"Sunlife GOF DNC", "Unknown"},
            {"Sunlife GOF Customer Referral", "Unknown"},
            {"Sunlife GOF(FLI)", "Unknown"},
            {"Sunlife GOF (FLI) DNC", "Unknown"},
            {"Sunlife GOF Expired", "Unknown"},
            {"SunLife Hotkeys", "Unknown"},
            {"SunLife Inbound", "Unknown"},
            {"SunLife Customer Referral", "Unknown"},
            {"Swinton Hotkeys", "Unknown"},
            {"Trafix Media ", "Unknown"},
            {"VeroCover", "Unknown"},
            {"Visionary Markets", "Unknown"},
            {"Visionary Markets Sat", "Unknown"},
            {"Visionary Markets Sun", "Unknown"},
            {"Visionary Markets Social", "Unknown"},
            {"Apply Online", "Rejected"},
            {"Apply Online Sat", "Rejected"},
            {"Apply Online Sun", "Rejected"},
            {"Apply Online INCOMPLETE", "Rejected"},
            {"Apply Online INCOMPLETE Sat", "Rejected"},
            {"Apply Online INCOMPLETE Sun", "Rejected"},
            {"Aspect Webmedia", "Rejected"},
            {"Aspect Webmedia Sat", "Rejected"},
            {"Aspect Webmedia Sun", "Rejected"},
            {"Best Health Policy RA", "Rejected"},
            {"Best Health Policy RA Sat", "Rejected"},
            {"Best Health Policy RA Sun", "Rejected"},
            {"Cavendish", "Rejected"},
            {"Cavendish Dec", "Rejected"},
            {"Cavendish Dec - DNC", "Rejected"},
            {"Cavendish Dec - Hotkey", "Rejected"},
            {"Cavendish - DNC", "Rejected"},
            {"Cavendish Dec Customer Referral", "Rejected"},
            {"Cavendish - Hotkey", "Rejected"},
            {"Cavendish Customer Referral", "Rejected"},
            {"clixel", "Rejected"},
            {"CompareLife", "Rejected"},
            {"clixel RA", "Rejected"},
            {"Conectia", "Rejected"},
            {"Deal Direct FS", "Rejected"},
            {"DST Team", "Rejected"},
            {"Dove Insurance", "Rejected"},
            {"e-Finity", "Rejected"},
            {"Engaged Solutions", "Rejected"},
            {"eHealthCompare RA", "Rejected"},
            {"eHealthCompare RA Sat", "Rejected"},
            {"eHealthCompare RA Sun", "Rejected"},
            {"eprospects", "Rejected"},
            {"eprospect SAT", "Rejected"},
            {"eprospect SUN", "Rejected"},
            {"Esmart", "Rejected"},
            {"Esmart Sat", "Rejected"},
            {"Esmart Sun", "Rejected"},
            {"finance_leads_online", "Rejected"},
            {"50PlusLife.co.uk", "Rejected"},
            {"Google", "Rejected"},
            {"Hotkey(Internal)", "Rejected"},
            {"HotKey Lead", "Rejected"},
            {"Hotkey(Cavendish)", "Rejected"},
            {"Hotkey(SunLife FLI)", "Rejected"},
            {"Hotkey(SunLife GOF)", "Rejected"},
            {"Impressia", "Rejected"},
            {"internal", "Rejected"},
            {"Kamicom", "Rejected"},
            {"leadbay", "Rejected"},
            {"LeadStream", "Rejected"},
            {"LeadStream Sat", "Rejected"},
            {"LeadStream Sun", "Rejected"},
            {"Look For Health RA", "Rejected"},
            {"Look For Health RA Sat", "Rejected"},
            {"Look For Health RA Sun", "Rejected"},
            {"look_for_life", "Rejected"},
            {"Look For Life RA", "Rejected"},
            {"Look For Life RA SAT", "Rejected"},
            {"Look For Life RA SUN", "Rejected"},
            {"LOANS REFERRAL", "Rejected"},
            {"leadstream", "Rejected"},
            {"leadstream Sat", "Rejected"},
            {"leadstream Sun", "Rejected"},
            {"livesure", "Rejected"},
            {"Livesure RA", "Rejected"},
            {"Livesure RA SAT", "Rejected"},
            {"Livesure RA SUN", "Rejected"},
            {"michael_anthony", "Rejected"},
            {"michael_anthony SAT", "Rejected"},
            {"michael_anthony SUN", "Rejected"},
            {"michael_anthony ADD", "Rejected"},
            {"MA WOL", "Rejected"},
            {"MA WOL Sat", "Rejected"},
            {"MA WOL Sun", "Rejected"},
            {"MA WOL ADD", "Rejected"},
            {"MA Switch", "Rejected"},
            {"MA Switch Sat", "Rejected"},
            {"MA Switch Sun", "Rejected"},
            {"michael_anthony COMM", "Rejected"},
            {"michael_anthony COMM SAT", "Rejected"},
            {"michael_anthony COMM SUN", "Rejected"},
            {"Baby Hotkey", "Rejected"},
            {"Business Leads", "Rejected"},
            {"BTQ Hotkey", "Rejected"},
            {"BuyLife", "Rejected"},
            {"First to Market", "Rejected"},
            {"MA Inbound", "Rejected"},
            {"Niche Data", "Rejected"},
            {"Niche Hot Key", "Rejected"},
            {"OSL", "Rejected"},
            {"www.protected.co.uk", "Rejected"},
            {"re-assured.co.uk", "Rejected"},
            {"Customer Referral", "Rejected"},
            {"SYN", "Rejected"},
            {"melodi", "Rejected"},
            {"Openwork", "Rejected"},
            {"Protect4Life", "Rejected"},
            {"premier_leads", "Rejected"},
            {"premier_leads Sat", "Rejected"},
            {"premier_leads Sun", "Rejected"},
            {"PMI Advisor Callback", "Rejected"},
            {"PMI Advisor Callback Sat", "Rejected"},
            {"PMI Advisor Callback Sun", "Rejected"},
            {"PMI Advisor Full Lead", "Rejected"},
            {"PMI Advisor Full Lead Sat", "Rejected"},
            {"PMI Advisor Full Lead Sun", "Rejected"},
            {"PMI Pre CRM", "Rejected"},
            {"Polly.co.uk", "Rejected"},
            {"Polly.co.uk Sat", "Rejected"},
            {"Polly.co.uk Sun", "Rejected"},
            {"Provident", "Rejected"},
            {"Quote Me Now", "Rejected"},
            {"QSM Incentivised", "Rejected"},
            {"QSM NotIncentivised", "Rejected"},
            {"Quote Searcher", "Rejected"},
            {"Quintessential", "Rejected"},
            {"Quintessential Sat", "Rejected"},
            {"Quintessential Sun", "Rejected"},
            {"Reassured Archive S", "Rejected"},
            {"Reassured Archive J", "Rejected"},
            {"Reassured Health", "Rejected"},
            {"Reassured Life", "Rejected"},
            {"RA Email SurePolicy", "Rejected"},
            {"RA Email SurePolicy SAT", "Rejected"},
            {"RA Email SurePolicy SUN", "Rejected"},
            {"RA PPC SureLoan", "Rejected"},
            {"RA PPC SureLoan Sat", "Rejected"},
            {"RA PPC SureLoan Sun", "Rejected"},
            {"RA PPC SurePolicy", "Rejected"},
            {"RA PPC SurePolicy SAT", "Rejected"},
            {"RA PPC SurePolicy SUN", "Rejected"},
            {"PMI Referral", "Rejected"},
            {"PMI Client", "Rejected"},
            {"Reassured Marketing", "Rejected"},
            {"Reassured Marketing Sat", "Rejected"},
            {"Reassured Marketing Sun", "Rejected"},
            {"Reassured Marketing PMI", "Rejected"},
            {"Reassured Marketing PMI SAT", "Rejected"},
            {"Reassured Marketing PMI SUN", "Rejected"},
            {"Reassured Marketing PPC", "Rejected"},
            {"RA Shared Lead", "Rejected"},
            {"RA Website", "Rejected"},
            {"RA Website PMI", "Rejected"},
            {"SunLife", "Rejected"},
            {"SunLife Mature", "Rejected"},
            {"SunLife Declined", "Rejected"},
            {"SunLife - 45 day Expired", "Rejected"},
            {"Sunlife GOF Capped", "Rejected"},
            {"Sunlife GOF Capped DNC", "Rejected"},
            {"Sunlife GOF", "Rejected"},
            {"Sunlife GOF DNC", "Rejected"},
            {"Sunlife GOF Customer Referral", "Rejected"},
            {"Sunlife GOF(FLI)", "Rejected"},
            {"Sunlife GOF (FLI) DNC", "Rejected"},
            {"Sunlife GOF Expired", "Rejected"},
            {"SunLife Hotkeys", "Rejected"},
            {"SunLife Inbound", "Rejected"},
            {"SunLife Customer Referral", "Rejected"},
            {"Swinton Hotkeys", "Rejected"},
            {"Trafix Media ", "Rejected"},
            {"VeroCover", "Rejected"},
            {"Visionary Markets", "Rejected"},
            {"Visionary Markets Sat", "Rejected"},
            {"Visionary Markets Sun", "Rejected"},
            {"Visionary Markets Social", "Rejected"}
    };
}
