package TestPrep;

/**
 * Created by hfletcher on 19/06/2018.
 */
public class AllLeadProvidersThree {

    public static String[][] AllLeadProviders = new String[][]{

            {"Apply Online", "Fake"},
            {"Apply Online Sat", "Fake"},
            {"Apply Online Sun", "Fake"},
            {"Apply Online INCOMPLETE", "Fake"},
            {"Apply Online INCOMPLETE Sat", "Fake"},
            {"Apply Online INCOMPLETE Sun", "Fake"},
            {"Aspect Webmedia", "Fake"},
            {"Aspect Webmedia Sat", "Fake"},
            {"Aspect Webmedia Sun", "Fake"},
            {"Best Health Policy RA", "Fake"},
            {"Best Health Policy RA Sat", "Fake"},
            {"Best Health Policy RA Sun", "Fake"},
            {"Cavendish", "Fake"},
            {"Cavendish Dec", "Fake"},
            {"Cavendish Dec - DNC", "Fake"},
            {"Cavendish Dec - Hotkey", "Fake"},
            {"Cavendish - DNC", "Fake"},
            {"Cavendish Dec Customer Referral", "Fake"},
            {"Cavendish - Hotkey", "Fake"},
            {"Cavendish Customer Referral", "Fake"},
            {"clixel", "Fake"},
            {"CompareLife", "Fake"},
            {"clixel RA", "Fake"},
            {"Conectia", "Fake"},
            {"Deal Direct FS", "Fake"},
            {"DST Team", "Fake"},
            {"Dove Insurance", "Fake"},
            {"e-Finity", "Fake"},
            {"Engaged Solutions", "Fake"},
            {"eHealthCompare RA", "Fake"},
            {"eHealthCompare RA Sat", "Fake"},
            {"eHealthCompare RA Sun", "Fake"},
            {"eprospects", "Fake"},
            {"eprospect SAT", "Fake"},
            {"eprospect SUN", "Fake"},
            {"Esmart", "Fake"},
            {"Esmart Sat", "Fake"},
            {"Esmart Sun", "Fake"},
            {"finance_leads_online", "Fake"},
            {"50PlusLife.co.uk", "Fake"},
            {"Google", "Fake"},
            {"Hotkey(Internal)", "Fake"},
            {"HotKey Lead", "Fake"},
            {"Hotkey(Cavendish)", "Fake"},
            {"Hotkey(SunLife FLI)", "Fake"},
            {"Hotkey(SunLife GOF)", "Fake"},
            {"Impressia", "Fake"},
            {"internal", "Fake"},
            {"Kamicom", "Fake"},
            {"leadbay", "Fake"},
            {"LeadStream", "Fake"},
            {"LeadStream Sat", "Fake"},
            {"LeadStream Sun", "Fake"},
            {"Look For Health RA", "Fake"},
            {"Look For Health RA Sat", "Fake"},
            {"Look For Health RA Sun", "Fake"},
            {"look_for_life", "Fake"},
            {"Look For Life RA", "Fake"},
            {"Look For Life RA SAT", "Fake"},
            {"Look For Life RA SUN", "Fake"},
            {"LOANS REFERRAL", "Fake"},
            {"leadstream", "Fake"},
            {"leadstream Sat", "Fake"},
            {"leadstream Sun", "Fake"},
            {"livesure", "Fake"},
            {"Livesure RA", "Fake"},
            {"Livesure RA SAT", "Fake"},
            {"Livesure RA SUN", "Fake"},
            {"michael_anthony", "Fake"},
            {"michael_anthony SAT", "Fake"},
            {"michael_anthony SUN", "Fake"},
            {"michael_anthony ADD", "Fake"},
            {"MA WOL", "Fake"},
            {"MA WOL Sat", "Fake"},
            {"MA WOL Sun", "Fake"},
            {"MA WOL ADD", "Fake"},
            {"MA Switch", "Fake"},
            {"MA Switch Sat", "Fake"},
            {"MA Switch Sun", "Fake"},
            {"michael_anthony COMM", "Fake"},
            {"michael_anthony COMM SAT", "Fake"},
            {"michael_anthony COMM SUN", "Fake"},
            {"Baby Hotkey", "Fake"},
            {"Business Leads", "Fake"},
            {"BTQ Hotkey", "Fake"},
            {"BuyLife", "Fake"},
            {"First to Market", "Fake"},
            {"MA Inbound", "Fake"},
            {"Niche Data", "Fake"},
            {"Niche Hot Key", "Fake"},
            {"OSL", "Fake"},
            {"www.protected.co.uk", "Fake"},
            {"re-assured.co.uk", "Fake"},
            {"Customer Referral", "Fake"},
            {"SYN", "Fake"},
            {"melodi", "Fake"},
            {"Openwork", "Fake"},
            {"Protect4Life", "Fake"},
            {"premier_leads", "Fake"},
            {"premier_leads Sat", "Fake"},
            {"premier_leads Sun", "Fake"},
            {"PMI Advisor Callback", "Fake"},
            {"PMI Advisor Callback Sat", "Fake"},
            {"PMI Advisor Callback Sun", "Fake"},
            {"PMI Advisor Full Lead", "Fake"},
            {"PMI Advisor Full Lead Sat", "Fake"},
            {"PMI Advisor Full Lead Sun", "Fake"},
            {"PMI Pre CRM", "Fake"},
            {"Polly.co.uk", "Fake"},
            {"Polly.co.uk Sat", "Fake"},
            {"Polly.co.uk Sun", "Fake"},
            {"Provident", "Fake"},
            {"Quote Me Now", "Fake"},
            {"QSM Incentivised", "Fake"},
            {"QSM NotIncentivised", "Fake"},
            {"Quote Searcher", "Fake"},
            {"Quintessential", "Fake"},
            {"Quintessential Sat", "Fake"},
            {"Quintessential Sun", "Fake"},
            {"Reassured Archive S", "Fake"},
            {"Reassured Archive J", "Fake"},
            {"Reassured Health", "Fake"},
            {"Reassured Life", "Fake"},
            {"RA Email SurePolicy", "Fake"},
            {"RA Email SurePolicy SAT", "Fake"},
            {"RA Email SurePolicy SUN", "Fake"},
            {"RA PPC SureLoan", "Fake"},
            {"RA PPC SureLoan Sat", "Fake"},
            {"RA PPC SureLoan Sun", "Fake"},
            {"RA PPC SurePolicy", "Fake"},
            {"RA PPC SurePolicy SAT", "Fake"},
            {"RA PPC SurePolicy SUN", "Fake"},
            {"PMI Referral", "Fake"},
            {"PMI Client", "Fake"},
            {"Reassured Marketing", "Fake"},
            {"Reassured Marketing Sat", "Fake"},
            {"Reassured Marketing Sun", "Fake"},
            {"Reassured Marketing PMI", "Fake"},
            {"Reassured Marketing PMI SAT", "Fake"},
            {"Reassured Marketing PMI SUN", "Fake"},
            {"Reassured Marketing PPC", "Fake"},
            {"RA Shared Lead", "Fake"},
            {"RA Website", "Fake"},
            {"RA Website PMI", "Fake"},
            {"SunLife", "Fake"},
            {"SunLife Mature", "Fake"},
            {"SunLife Declined", "Fake"},
            {"SunLife - 45 day Expired", "Fake"},
            {"Sunlife GOF Capped", "Fake"},
            {"Sunlife GOF Capped DNC", "Fake"},
            {"Sunlife GOF", "Fake"},
            {"Sunlife GOF DNC", "Fake"},
            {"Sunlife GOF Customer Referral", "Fake"},
            {"Sunlife GOF(FLI)", "Fake"},
            {"Sunlife GOF (FLI) DNC", "Fake"},
            {"Sunlife GOF Expired", "Fake"},
            {"SunLife Hotkeys", "Fake"},
            {"SunLife Inbound", "Fake"},
            {"SunLife Customer Referral", "Fake"},
            {"Swinton Hotkeys", "Fake"},
            {"Trafix Media ", "Fake"},
            {"VeroCover", "Fake"},
            {"Visionary Markets", "Fake"},
            {"Visionary Markets Sat", "Fake"},
            {"Visionary Markets Sun", "Fake"},
            {"Visionary Markets Social", "Fake"},
            {"Apply Online", "Duplicate"},
            {"Apply Online Sat", "Duplicate"},
            {"Apply Online Sun", "Duplicate"},
            {"Apply Online INCOMPLETE", "Duplicate"},
            {"Apply Online INCOMPLETE Sat", "Duplicate"},
            {"Apply Online INCOMPLETE Sun", "Duplicate"},
            {"Aspect Webmedia", "Duplicate"},
            {"Aspect Webmedia Sat", "Duplicate"},
            {"Aspect Webmedia Sun", "Duplicate"},
            {"Best Health Policy RA", "Duplicate"},
            {"Best Health Policy RA Sat", "Duplicate"},
            {"Best Health Policy RA Sun", "Duplicate"},
            {"Cavendish", "Duplicate"},
            {"Cavendish Dec", "Duplicate"},
            {"Cavendish Dec - DNC", "Duplicate"},
            {"Cavendish Dec - Hotkey", "Duplicate"},
            {"Cavendish - DNC", "Duplicate"},
            {"Cavendish Dec Customer Referral", "Duplicate"},
            {"Cavendish - Hotkey", "Duplicate"},
            {"Cavendish Customer Referral", "Duplicate"},
            {"clixel", "Duplicate"},
            {"CompareLife", "Duplicate"},
            {"clixel RA", "Duplicate"},
            {"Conectia", "Duplicate"},
            {"Deal Direct FS", "Duplicate"},
            {"DST Team", "Duplicate"},
            {"Dove Insurance", "Duplicate"},
            {"e-Finity", "Duplicate"},
            {"Engaged Solutions", "Duplicate"},
            {"eHealthCompare RA", "Duplicate"},
            {"eHealthCompare RA Sat", "Duplicate"},
            {"eHealthCompare RA Sun", "Duplicate"},
            {"eprospects", "Duplicate"},
            {"eprospect SAT", "Duplicate"},
            {"eprospect SUN", "Duplicate"},
            {"Esmart", "Duplicate"},
            {"Esmart Sat", "Duplicate"},
            {"Esmart Sun", "Duplicate"},
            {"finance_leads_online", "Duplicate"},
            {"50PlusLife.co.uk", "Duplicate"},
            {"Google", "Duplicate"},
            {"Hotkey(Internal)", "Duplicate"},
            {"HotKey Lead", "Duplicate"},
            {"Hotkey(Cavendish)", "Duplicate"},
            {"Hotkey(SunLife FLI)", "Duplicate"},
            {"Hotkey(SunLife GOF)", "Duplicate"},
            {"Impressia", "Duplicate"},
            {"internal", "Duplicate"},
            {"Kamicom", "Duplicate"},
            {"leadbay", "Duplicate"},
            {"LeadStream", "Duplicate"},
            {"LeadStream Sat", "Duplicate"},
            {"LeadStream Sun", "Duplicate"},
            {"Look For Health RA", "Duplicate"},
            {"Look For Health RA Sat", "Duplicate"},
            {"Look For Health RA Sun", "Duplicate"},
            {"look_for_life", "Duplicate"},
            {"Look For Life RA", "Duplicate"},
            {"Look For Life RA SAT", "Duplicate"},
            {"Look For Life RA SUN", "Duplicate"},
            {"LOANS REFERRAL", "Duplicate"},
            {"leadstream", "Duplicate"},
            {"leadstream Sat", "Duplicate"},
            {"leadstream Sun", "Duplicate"},
            {"livesure", "Duplicate"},
            {"Livesure RA", "Duplicate"},
            {"Livesure RA SAT", "Duplicate"},
            {"Livesure RA SUN", "Duplicate"},
            {"michael_anthony", "Duplicate"},
            {"michael_anthony SAT", "Duplicate"},
            {"michael_anthony SUN", "Duplicate"},
            {"michael_anthony ADD", "Duplicate"},
            {"MA WOL", "Duplicate"},
            {"MA WOL Sat", "Duplicate"},
            {"MA WOL Sun", "Duplicate"},
            {"MA WOL ADD", "Duplicate"},
            {"MA Switch", "Duplicate"},
            {"MA Switch Sat", "Duplicate"},
            {"MA Switch Sun", "Duplicate"},
            {"michael_anthony COMM", "Duplicate"},
            {"michael_anthony COMM SAT", "Duplicate"},
            {"michael_anthony COMM SUN", "Duplicate"},
            {"Baby Hotkey", "Duplicate"},
            {"Business Leads", "Duplicate"},
            {"BTQ Hotkey", "Duplicate"},
            {"BuyLife", "Duplicate"},
            {"First to Market", "Duplicate"},
            {"MA Inbound", "Duplicate"},
            {"Niche Data", "Duplicate"},
            {"Niche Hot Key", "Duplicate"},
            {"OSL", "Duplicate"},
            {"www.protected.co.uk", "Duplicate"},
            {"re-assured.co.uk", "Duplicate"},
            {"Customer Referral", "Duplicate"},
            {"SYN", "Duplicate"},
            {"melodi", "Duplicate"},
            {"Openwork", "Duplicate"},
            {"Protect4Life", "Duplicate"},
            {"premier_leads", "Duplicate"},
            {"premier_leads Sat", "Duplicate"},
            {"premier_leads Sun", "Duplicate"},
            {"PMI Advisor Callback", "Duplicate"},
            {"PMI Advisor Callback Sat", "Duplicate"},
            {"PMI Advisor Callback Sun", "Duplicate"},
            {"PMI Advisor Full Lead", "Duplicate"},
            {"PMI Advisor Full Lead Sat", "Duplicate"},
            {"PMI Advisor Full Lead Sun", "Duplicate"},
            {"PMI Pre CRM", "Duplicate"},
            {"Polly.co.uk", "Duplicate"},
            {"Polly.co.uk Sat", "Duplicate"},
            {"Polly.co.uk Sun", "Duplicate"},
            {"Provident", "Duplicate"},
            {"Quote Me Now", "Duplicate"},
            {"QSM Incentivised", "Duplicate"},
            {"QSM NotIncentivised", "Duplicate"},
            {"Quote Searcher", "Duplicate"},
            {"Quintessential", "Duplicate"},
            {"Quintessential Sat", "Duplicate"},
            {"Quintessential Sun", "Duplicate"},
            {"Reassured Archive S", "Duplicate"},
            {"Reassured Archive J", "Duplicate"},
            {"Reassured Health", "Duplicate"},
            {"Reassured Life", "Duplicate"},
            {"RA Email SurePolicy", "Duplicate"},
            {"RA Email SurePolicy SAT", "Duplicate"},
            {"RA Email SurePolicy SUN", "Duplicate"},
            {"RA PPC SureLoan", "Duplicate"},
            {"RA PPC SureLoan Sat", "Duplicate"},
            {"RA PPC SureLoan Sun", "Duplicate"},
            {"RA PPC SurePolicy", "Duplicate"},
            {"RA PPC SurePolicy SAT", "Duplicate"},
            {"RA PPC SurePolicy SUN", "Duplicate"},
            {"PMI Referral", "Duplicate"},
            {"PMI Client", "Duplicate"},
            {"Reassured Marketing", "Duplicate"},
            {"Reassured Marketing Sat", "Duplicate"},
            {"Reassured Marketing Sun", "Duplicate"},
            {"Reassured Marketing PMI", "Duplicate"},
            {"Reassured Marketing PMI SAT", "Duplicate"},
            {"Reassured Marketing PMI SUN", "Duplicate"},
            {"Reassured Marketing PPC", "Duplicate"},
            {"RA Shared Lead", "Duplicate"},
            {"RA Website", "Duplicate"},
            {"RA Website PMI", "Duplicate"},
            {"SunLife", "Duplicate"},
            {"SunLife Mature", "Duplicate"},
            {"SunLife Declined", "Duplicate"},
            {"SunLife - 45 day Expired", "Duplicate"},
            {"Sunlife GOF Capped", "Duplicate"},
            {"Sunlife GOF Capped DNC", "Duplicate"},
            {"Sunlife GOF", "Duplicate"},
            {"Sunlife GOF DNC", "Duplicate"},
            {"Sunlife GOF Customer Referral", "Duplicate"},
            {"Sunlife GOF(FLI)", "Duplicate"},
            {"Sunlife GOF (FLI) DNC", "Duplicate"},
            {"Sunlife GOF Expired", "Duplicate"},
            {"SunLife Hotkeys", "Duplicate"},
            {"SunLife Inbound", "Duplicate"},
            {"SunLife Customer Referral", "Duplicate"},
            {"Swinton Hotkeys", "Duplicate"},
            {"Trafix Media ", "Duplicate"},
            {"VeroCover", "Duplicate"},
            {"Visionary Markets", "Duplicate"},
            {"Visionary Markets Sat", "Duplicate"},
            {"Visionary Markets Sun", "Duplicate"},
            {"Visionary Markets Social", "Duplicate"},
            {"Apply Online", "Turned Down"},
            {"Apply Online Sat", "Turned Down"},
            {"Apply Online Sun", "Turned Down"},
            {"Apply Online INCOMPLETE", "Turned Down"},
            {"Apply Online INCOMPLETE Sat", "Turned Down"},
            {"Apply Online INCOMPLETE Sun", "Turned Down"},
            {"Aspect Webmedia", "Turned Down"},
            {"Aspect Webmedia Sat", "Turned Down"},
            {"Aspect Webmedia Sun", "Turned Down"},
            {"Best Health Policy RA", "Turned Down"},
            {"Best Health Policy RA Sat", "Turned Down"},
            {"Best Health Policy RA Sun", "Turned Down"},
            {"Cavendish", "Turned Down"},
            {"Cavendish Dec", "Turned Down"},
            {"Cavendish Dec - DNC", "Turned Down"},
            {"Cavendish Dec - Hotkey", "Turned Down"},
            {"Cavendish - DNC", "Turned Down"},
            {"Cavendish Dec Customer Referral", "Turned Down"},
            {"Cavendish - Hotkey", "Turned Down"},
            {"Cavendish Customer Referral", "Turned Down"},
            {"clixel", "Turned Down"},
            {"CompareLife", "Turned Down"},
            {"clixel RA", "Turned Down"},
            {"Conectia", "Turned Down"},
            {"Deal Direct FS", "Turned Down"},
            {"DST Team", "Turned Down"},
            {"Dove Insurance", "Turned Down"},
            {"e-Finity", "Turned Down"},
            {"Engaged Solutions", "Turned Down"},
            {"eHealthCompare RA", "Turned Down"},
            {"eHealthCompare RA Sat", "Turned Down"},
            {"eHealthCompare RA Sun", "Turned Down"},
            {"eprospects", "Turned Down"},
            {"eprospect SAT", "Turned Down"},
            {"eprospect SUN", "Turned Down"},
            {"Esmart", "Turned Down"},
            {"Esmart Sat", "Turned Down"},
            {"Esmart Sun", "Turned Down"},
            {"finance_leads_online", "Turned Down"},
            {"50PlusLife.co.uk", "Turned Down"},
            {"Google", "Turned Down"},
            {"Hotkey(Internal)", "Turned Down"},
            {"HotKey Lead", "Turned Down"},
            {"Hotkey(Cavendish)", "Turned Down"},
            {"Hotkey(SunLife FLI)", "Turned Down"},
            {"Hotkey(SunLife GOF)", "Turned Down"},
            {"Impressia", "Turned Down"},
            {"internal", "Turned Down"},
            {"Kamicom", "Turned Down"},
            {"leadbay", "Turned Down"},
            {"LeadStream", "Turned Down"},
            {"LeadStream Sat", "Turned Down"},
            {"LeadStream Sun", "Turned Down"},
            {"Look For Health RA", "Turned Down"},
            {"Look For Health RA Sat", "Turned Down"},
            {"Look For Health RA Sun", "Turned Down"},
            {"look_for_life", "Turned Down"},
            {"Look For Life RA", "Turned Down"},
            {"Look For Life RA SAT", "Turned Down"},
            {"Look For Life RA SUN", "Turned Down"},
            {"LOANS REFERRAL", "Turned Down"},
            {"leadstream", "Turned Down"},
            {"leadstream Sat", "Turned Down"},
            {"leadstream Sun", "Turned Down"},
            {"livesure", "Turned Down"},
            {"Livesure RA", "Turned Down"},
            {"Livesure RA SAT", "Turned Down"},
            {"Livesure RA SUN", "Turned Down"},
            {"michael_anthony", "Turned Down"},
            {"michael_anthony SAT", "Turned Down"},
            {"michael_anthony SUN", "Turned Down"},
            {"michael_anthony ADD", "Turned Down"},
            {"MA WOL", "Turned Down"},
            {"MA WOL Sat", "Turned Down"},
            {"MA WOL Sun", "Turned Down"},
            {"MA WOL ADD", "Turned Down"},
            {"MA Switch", "Turned Down"},
            {"MA Switch Sat", "Turned Down"},
            {"MA Switch Sun", "Turned Down"},
            {"michael_anthony COMM", "Turned Down"},
            {"michael_anthony COMM SAT", "Turned Down"},
            {"michael_anthony COMM SUN", "Turned Down"},
            {"Baby Hotkey", "Turned Down"},
            {"Business Leads", "Turned Down"},
            {"BTQ Hotkey", "Turned Down"},
            {"BuyLife", "Turned Down"},
            {"First to Market", "Turned Down"},
            {"MA Inbound", "Turned Down"},
            {"Niche Data", "Turned Down"},
            {"Niche Hot Key", "Turned Down"},
            {"OSL", "Turned Down"},
            {"www.protected.co.uk", "Turned Down"},
            {"re-assured.co.uk", "Turned Down"},
            {"Customer Referral", "Turned Down"},
            {"SYN", "Turned Down"},
            {"melodi", "Turned Down"},
            {"Openwork", "Turned Down"},
            {"Protect4Life", "Turned Down"},
            {"premier_leads", "Turned Down"},
            {"premier_leads Sat", "Turned Down"},
            {"premier_leads Sun", "Turned Down"},
            {"PMI Advisor Callback", "Turned Down"},
            {"PMI Advisor Callback Sat", "Turned Down"},
            {"PMI Advisor Callback Sun", "Turned Down"},
            {"PMI Advisor Full Lead", "Turned Down"},
            {"PMI Advisor Full Lead Sat", "Turned Down"},
            {"PMI Advisor Full Lead Sun", "Turned Down"},
            {"PMI Pre CRM", "Turned Down"},
            {"Polly.co.uk", "Turned Down"},
            {"Polly.co.uk Sat", "Turned Down"},
            {"Polly.co.uk Sun", "Turned Down"},
            {"Provident", "Turned Down"},
            {"Quote Me Now", "Turned Down"},
            {"QSM Incentivised", "Turned Down"},
            {"QSM NotIncentivised", "Turned Down"},
            {"Quote Searcher", "Turned Down"},
            {"Quintessential", "Turned Down"},
            {"Quintessential Sat", "Turned Down"},
            {"Quintessential Sun", "Turned Down"},
            {"Reassured Archive S", "Turned Down"},
            {"Reassured Archive J", "Turned Down"},
            {"Reassured Health", "Turned Down"},
            {"Reassured Life", "Turned Down"},
            {"RA Email SurePolicy", "Turned Down"},
            {"RA Email SurePolicy SAT", "Turned Down"},
            {"RA Email SurePolicy SUN", "Turned Down"},
            {"RA PPC SureLoan", "Turned Down"},
            {"RA PPC SureLoan Sat", "Turned Down"},
            {"RA PPC SureLoan Sun", "Turned Down"},
            {"RA PPC SurePolicy", "Turned Down"},
            {"RA PPC SurePolicy SAT", "Turned Down"},
            {"RA PPC SurePolicy SUN", "Turned Down"},
            {"PMI Referral", "Turned Down"},
            {"PMI Client", "Turned Down"},
            {"Reassured Marketing", "Turned Down"},
            {"Reassured Marketing Sat", "Turned Down"},
            {"Reassured Marketing Sun", "Turned Down"},
            {"Reassured Marketing PMI", "Turned Down"},
            {"Reassured Marketing PMI SAT", "Turned Down"},
            {"Reassured Marketing PMI SUN", "Turned Down"},
            {"Reassured Marketing PPC", "Turned Down"},
            {"RA Shared Lead", "Turned Down"},
            {"RA Website", "Turned Down"},
            {"RA Website PMI", "Turned Down"},
            {"SunLife", "Turned Down"},
            {"SunLife Mature", "Turned Down"},
            {"SunLife Declined", "Turned Down"},
            {"SunLife - 45 day Expired", "Turned Down"},
            {"Sunlife GOF Capped", "Turned Down"},
            {"Sunlife GOF Capped DNC", "Turned Down"},
            {"Sunlife GOF", "Turned Down"},
            {"Sunlife GOF DNC", "Turned Down"},
            {"Sunlife GOF Customer Referral", "Turned Down"},
            {"Sunlife GOF(FLI)", "Turned Down"},
            {"Sunlife GOF (FLI) DNC", "Turned Down"},
            {"Sunlife GOF Expired", "Turned Down"},
            {"SunLife Hotkeys", "Turned Down"},
            {"SunLife Inbound", "Turned Down"},
            {"SunLife Customer Referral", "Turned Down"},
            {"Swinton Hotkeys", "Turned Down"},
            {"Trafix Media ", "Turned Down"},
            {"VeroCover", "Turned Down"},
            {"Visionary Markets", "Turned Down"},
            {"Visionary Markets Sat", "Turned Down"},
            {"Visionary Markets Sun", "Turned Down"},
            {"Visionary Markets Social", "Turned Down"},
            {"Apply Online", "Quoted"},
            {"Apply Online Sat", "Quoted"},
            {"Apply Online Sun", "Quoted"},
            {"Apply Online INCOMPLETE", "Quoted"},
            {"Apply Online INCOMPLETE Sat", "Quoted"},
            {"Apply Online INCOMPLETE Sun", "Quoted"},
            {"Aspect Webmedia", "Quoted"},
            {"Aspect Webmedia Sat", "Quoted"},
            {"Aspect Webmedia Sun", "Quoted"},
            {"Best Health Policy RA", "Quoted"},
            {"Best Health Policy RA Sat", "Quoted"},
            {"Best Health Policy RA Sun", "Quoted"},
            {"Cavendish", "Quoted"},
            {"Cavendish Dec", "Quoted"},
            {"Cavendish Dec - DNC", "Quoted"},
            {"Cavendish Dec - Hotkey", "Quoted"},
            {"Cavendish - DNC", "Quoted"},
            {"Cavendish Dec Customer Referral", "Quoted"},
            {"Cavendish - Hotkey", "Quoted"},
            {"Cavendish Customer Referral", "Quoted"},
            {"clixel", "Quoted"},
            {"CompareLife", "Quoted"},
            {"clixel RA", "Quoted"},
            {"Conectia", "Quoted"},
            {"Deal Direct FS", "Quoted"},
            {"DST Team", "Quoted"},
            {"Dove Insurance", "Quoted"},
            {"e-Finity", "Quoted"},
            {"Engaged Solutions", "Quoted"},
            {"eHealthCompare RA", "Quoted"},
            {"eHealthCompare RA Sat", "Quoted"},
            {"eHealthCompare RA Sun", "Quoted"},
            {"eprospects", "Quoted"},
            {"eprospect SAT", "Quoted"},
            {"eprospect SUN", "Quoted"},
            {"Esmart", "Quoted"},
            {"Esmart Sat", "Quoted"},
            {"Esmart Sun", "Quoted"},
            {"finance_leads_online", "Quoted"},
            {"50PlusLife.co.uk", "Quoted"},
            {"Google", "Quoted"},
            {"Hotkey(Internal)", "Quoted"},
            {"HotKey Lead", "Quoted"},
            {"Hotkey(Cavendish)", "Quoted"},
            {"Hotkey(SunLife FLI)", "Quoted"},
            {"Hotkey(SunLife GOF)", "Quoted"},
            {"Impressia", "Quoted"},
            {"internal", "Quoted"},
            {"Kamicom", "Quoted"},
            {"leadbay", "Quoted"},
            {"LeadStream", "Quoted"},
            {"LeadStream Sat", "Quoted"},
            {"LeadStream Sun", "Quoted"},
            {"Look For Health RA", "Quoted"},
            {"Look For Health RA Sat", "Quoted"},
            {"Look For Health RA Sun", "Quoted"},
            {"look_for_life", "Quoted"},
            {"Look For Life RA", "Quoted"},
            {"Look For Life RA SAT", "Quoted"},
            {"Look For Life RA SUN", "Quoted"},
            {"LOANS REFERRAL", "Quoted"},
            {"leadstream", "Quoted"},
            {"leadstream Sat", "Quoted"},
            {"leadstream Sun", "Quoted"},
            {"livesure", "Quoted"},
            {"Livesure RA", "Quoted"},
            {"Livesure RA SAT", "Quoted"},
            {"Livesure RA SUN", "Quoted"},
            {"michael_anthony", "Quoted"},
            {"michael_anthony SAT", "Quoted"},
            {"michael_anthony SUN", "Quoted"},
            {"michael_anthony ADD", "Quoted"},
            {"MA WOL", "Quoted"},
            {"MA WOL Sat", "Quoted"},
            {"MA WOL Sun", "Quoted"},
            {"MA WOL ADD", "Quoted"},
            {"MA Switch", "Quoted"},
            {"MA Switch Sat", "Quoted"},
            {"MA Switch Sun", "Quoted"},
            {"michael_anthony COMM", "Quoted"},
            {"michael_anthony COMM SAT", "Quoted"},
            {"michael_anthony COMM SUN", "Quoted"},
            {"Baby Hotkey", "Quoted"},
            {"Business Leads", "Quoted"},
            {"BTQ Hotkey", "Quoted"},
            {"BuyLife", "Quoted"},
            {"First to Market", "Quoted"},
            {"MA Inbound", "Quoted"},
            {"Niche Data", "Quoted"},
            {"Niche Hot Key", "Quoted"},
            {"OSL", "Quoted"},
            {"www.protected.co.uk", "Quoted"},
            {"re-assured.co.uk", "Quoted"},
            {"Customer Referral", "Quoted"},
            {"SYN", "Quoted"},
            {"melodi", "Quoted"},
            {"Openwork", "Quoted"},
            {"Protect4Life", "Quoted"},
            {"premier_leads", "Quoted"},
            {"premier_leads Sat", "Quoted"},
            {"premier_leads Sun", "Quoted"},
            {"PMI Advisor Callback", "Quoted"},
            {"PMI Advisor Callback Sat", "Quoted"},
            {"PMI Advisor Callback Sun", "Quoted"},
            {"PMI Advisor Full Lead", "Quoted"},
            {"PMI Advisor Full Lead Sat", "Quoted"},
            {"PMI Advisor Full Lead Sun", "Quoted"},
            {"PMI Pre CRM", "Quoted"},
            {"Polly.co.uk", "Quoted"},
            {"Polly.co.uk Sat", "Quoted"},
            {"Polly.co.uk Sun", "Quoted"},
            {"Provident", "Quoted"},
            {"Quote Me Now", "Quoted"},
            {"QSM Incentivised", "Quoted"},
            {"QSM NotIncentivised", "Quoted"},
            {"Quote Searcher", "Quoted"},
            {"Quintessential", "Quoted"},
            {"Quintessential Sat", "Quoted"},
            {"Quintessential Sun", "Quoted"},
            {"Reassured Archive S", "Quoted"},
            {"Reassured Archive J", "Quoted"},
            {"Reassured Health", "Quoted"},
            {"Reassured Life", "Quoted"},
            {"RA Email SurePolicy", "Quoted"},
            {"RA Email SurePolicy SAT", "Quoted"},
            {"RA Email SurePolicy SUN", "Quoted"},
            {"RA PPC SureLoan", "Quoted"},
            {"RA PPC SureLoan Sat", "Quoted"},
            {"RA PPC SureLoan Sun", "Quoted"},
            {"RA PPC SurePolicy", "Quoted"},
            {"RA PPC SurePolicy SAT", "Quoted"},
            {"RA PPC SurePolicy SUN", "Quoted"},
            {"PMI Referral", "Quoted"},
            {"PMI Client", "Quoted"},
            {"Reassured Marketing", "Quoted"},
            {"Reassured Marketing Sat", "Quoted"},
            {"Reassured Marketing Sun", "Quoted"},
            {"Reassured Marketing PMI", "Quoted"},
            {"Reassured Marketing PMI SAT", "Quoted"},
            {"Reassured Marketing PMI SUN", "Quoted"},
            {"Reassured Marketing PPC", "Quoted"},
            {"RA Shared Lead", "Quoted"},
            {"RA Website", "Quoted"},
            {"RA Website PMI", "Quoted"},
            {"SunLife", "Quoted"},
            {"SunLife Mature", "Quoted"},
            {"SunLife Declined", "Quoted"},
            {"SunLife - 45 day Expired", "Quoted"},
            {"Sunlife GOF Capped", "Quoted"},
            {"Sunlife GOF Capped DNC", "Quoted"},
            {"Sunlife GOF", "Quoted"},
            {"Sunlife GOF DNC", "Quoted"},
            {"Sunlife GOF Customer Referral", "Quoted"},
            {"Sunlife GOF(FLI)", "Quoted"},
            {"Sunlife GOF (FLI) DNC", "Quoted"},
            {"Sunlife GOF Expired", "Quoted"},
            {"SunLife Hotkeys", "Quoted"},
            {"SunLife Inbound", "Quoted"},
            {"SunLife Customer Referral", "Quoted"},
            {"Swinton Hotkeys", "Quoted"},
            {"Trafix Media ", "Quoted"},
            {"VeroCover", "Quoted"},
            {"Visionary Markets", "Quoted"},
            {"Visionary Markets Sat", "Quoted"},
            {"Visionary Markets Sun", "Quoted"},
            {"Visionary Markets Social", "Quoted"},
            {"Apply Online", "Cannot Quote"},
            {"Apply Online Sat", "Cannot Quote"},
            {"Apply Online Sun", "Cannot Quote"},
            {"Apply Online INCOMPLETE", "Cannot Quote"},
            {"Apply Online INCOMPLETE Sat", "Cannot Quote"},
            {"Apply Online INCOMPLETE Sun", "Cannot Quote"},
            {"Aspect Webmedia", "Cannot Quote"},
            {"Aspect Webmedia Sat", "Cannot Quote"},
            {"Aspect Webmedia Sun", "Cannot Quote"},
            {"Best Health Policy RA", "Cannot Quote"},
            {"Best Health Policy RA Sat", "Cannot Quote"},
            {"Best Health Policy RA Sun", "Cannot Quote"},
            {"Cavendish", "Cannot Quote"},
            {"Cavendish Dec", "Cannot Quote"},
            {"Cavendish Dec - DNC", "Cannot Quote"},
            {"Cavendish Dec - Hotkey", "Cannot Quote"},
            {"Cavendish - DNC", "Cannot Quote"},
            {"Cavendish Dec Customer Referral", "Cannot Quote"},
            {"Cavendish - Hotkey", "Cannot Quote"},
            {"Cavendish Customer Referral", "Cannot Quote"},
            {"clixel", "Cannot Quote"},
            {"CompareLife", "Cannot Quote"},
            {"clixel RA", "Cannot Quote"},
            {"Conectia", "Cannot Quote"},
            {"Deal Direct FS", "Cannot Quote"},
            {"DST Team", "Cannot Quote"},
            {"Dove Insurance", "Cannot Quote"},
            {"e-Finity", "Cannot Quote"},
            {"Engaged Solutions", "Cannot Quote"},
            {"eHealthCompare RA", "Cannot Quote"},
            {"eHealthCompare RA Sat", "Cannot Quote"},
            {"eHealthCompare RA Sun", "Cannot Quote"},
            {"eprospects", "Cannot Quote"},
            {"eprospect SAT", "Cannot Quote"},
            {"eprospect SUN", "Cannot Quote"},
            {"Esmart", "Cannot Quote"},
            {"Esmart Sat", "Cannot Quote"},
            {"Esmart Sun", "Cannot Quote"},
            {"finance_leads_online", "Cannot Quote"},
            {"50PlusLife.co.uk", "Cannot Quote"},
            {"Google", "Cannot Quote"},
            {"Hotkey(Internal)", "Cannot Quote"},
            {"HotKey Lead", "Cannot Quote"},
            {"Hotkey(Cavendish)", "Cannot Quote"},
            {"Hotkey(SunLife FLI)", "Cannot Quote"},
            {"Hotkey(SunLife GOF)", "Cannot Quote"},
            {"Impressia", "Cannot Quote"},
            {"internal", "Cannot Quote"},
            {"Kamicom", "Cannot Quote"},
            {"leadbay", "Cannot Quote"},
            {"LeadStream", "Cannot Quote"},
            {"LeadStream Sat", "Cannot Quote"},
            {"LeadStream Sun", "Cannot Quote"},
            {"Look For Health RA", "Cannot Quote"},
            {"Look For Health RA Sat", "Cannot Quote"},
            {"Look For Health RA Sun", "Cannot Quote"},
            {"look_for_life", "Cannot Quote"},
            {"Look For Life RA", "Cannot Quote"},
            {"Look For Life RA SAT", "Cannot Quote"},
            {"Look For Life RA SUN", "Cannot Quote"},
            {"LOANS REFERRAL", "Cannot Quote"},
            {"leadstream", "Cannot Quote"},
            {"leadstream Sat", "Cannot Quote"},
            {"leadstream Sun", "Cannot Quote"},
            {"livesure", "Cannot Quote"},
            {"Livesure RA", "Cannot Quote"},
            {"Livesure RA SAT", "Cannot Quote"},
            {"Livesure RA SUN", "Cannot Quote"},
            {"michael_anthony", "Cannot Quote"},
            {"michael_anthony SAT", "Cannot Quote"},
            {"michael_anthony SUN", "Cannot Quote"},
            {"michael_anthony ADD", "Cannot Quote"},
            {"MA WOL", "Cannot Quote"},
            {"MA WOL Sat", "Cannot Quote"},
            {"MA WOL Sun", "Cannot Quote"},
            {"MA WOL ADD", "Cannot Quote"},
            {"MA Switch", "Cannot Quote"},
            {"MA Switch Sat", "Cannot Quote"},
            {"MA Switch Sun", "Cannot Quote"},
            {"michael_anthony COMM", "Cannot Quote"},
            {"michael_anthony COMM SAT", "Cannot Quote"},
            {"michael_anthony COMM SUN", "Cannot Quote"},
            {"Baby Hotkey", "Cannot Quote"},
            {"Business Leads", "Cannot Quote"},
            {"BTQ Hotkey", "Cannot Quote"},
            {"BuyLife", "Cannot Quote"},
            {"First to Market", "Cannot Quote"},
            {"MA Inbound", "Cannot Quote"},
            {"Niche Data", "Cannot Quote"},
            {"Niche Hot Key", "Cannot Quote"},
            {"OSL", "Cannot Quote"},
            {"www.protected.co.uk", "Cannot Quote"},
            {"re-assured.co.uk", "Cannot Quote"},
            {"Customer Referral", "Cannot Quote"},
            {"SYN", "Cannot Quote"},
            {"melodi", "Cannot Quote"},
            {"Openwork", "Cannot Quote"},
            {"Protect4Life", "Cannot Quote"},
            {"premier_leads", "Cannot Quote"},
            {"premier_leads Sat", "Cannot Quote"},
            {"premier_leads Sun", "Cannot Quote"},
            {"PMI Advisor Callback", "Cannot Quote"},
            {"PMI Advisor Callback Sat", "Cannot Quote"},
            {"PMI Advisor Callback Sun", "Cannot Quote"},
            {"PMI Advisor Full Lead", "Cannot Quote"},
            {"PMI Advisor Full Lead Sat", "Cannot Quote"},
            {"PMI Advisor Full Lead Sun", "Cannot Quote"},
            {"PMI Pre CRM", "Cannot Quote"},
            {"Polly.co.uk", "Cannot Quote"},
            {"Polly.co.uk Sat", "Cannot Quote"},
            {"Polly.co.uk Sun", "Cannot Quote"},
            {"Provident", "Cannot Quote"},
            {"Quote Me Now", "Cannot Quote"},
            {"QSM Incentivised", "Cannot Quote"},
            {"QSM NotIncentivised", "Cannot Quote"},
            {"Quote Searcher", "Cannot Quote"},
            {"Quintessential", "Cannot Quote"},
            {"Quintessential Sat", "Cannot Quote"},
            {"Quintessential Sun", "Cannot Quote"},
            {"Reassured Archive S", "Cannot Quote"},
            {"Reassured Archive J", "Cannot Quote"},
            {"Reassured Health", "Cannot Quote"},
            {"Reassured Life", "Cannot Quote"},
            {"RA Email SurePolicy", "Cannot Quote"},
            {"RA Email SurePolicy SAT", "Cannot Quote"},
            {"RA Email SurePolicy SUN", "Cannot Quote"},
            {"RA PPC SureLoan", "Cannot Quote"},
            {"RA PPC SureLoan Sat", "Cannot Quote"},
            {"RA PPC SureLoan Sun", "Cannot Quote"},
            {"RA PPC SurePolicy", "Cannot Quote"},
            {"RA PPC SurePolicy SAT", "Cannot Quote"},
            {"RA PPC SurePolicy SUN", "Cannot Quote"},
            {"PMI Referral", "Cannot Quote"},
            {"PMI Client", "Cannot Quote"},
            {"Reassured Marketing", "Cannot Quote"},
            {"Reassured Marketing Sat", "Cannot Quote"},
            {"Reassured Marketing Sun", "Cannot Quote"},
            {"Reassured Marketing PMI", "Cannot Quote"},
            {"Reassured Marketing PMI SAT", "Cannot Quote"},
            {"Reassured Marketing PMI SUN", "Cannot Quote"},
            {"Reassured Marketing PPC", "Cannot Quote"},
            {"RA Shared Lead", "Cannot Quote"},
            {"RA Website", "Cannot Quote"},
            {"RA Website PMI", "Cannot Quote"},
            {"SunLife", "Cannot Quote"},
            {"SunLife Mature", "Cannot Quote"},
            {"SunLife Declined", "Cannot Quote"},
            {"SunLife - 45 day Expired", "Cannot Quote"},
            {"Sunlife GOF Capped", "Cannot Quote"},
            {"Sunlife GOF Capped DNC", "Cannot Quote"},
            {"Sunlife GOF", "Cannot Quote"},
            {"Sunlife GOF DNC", "Cannot Quote"},
            {"Sunlife GOF Customer Referral", "Cannot Quote"},
            {"Sunlife GOF(FLI)", "Cannot Quote"},
            {"Sunlife GOF (FLI) DNC", "Cannot Quote"},
            {"Sunlife GOF Expired", "Cannot Quote"},
            {"SunLife Hotkeys", "Cannot Quote"},
            {"SunLife Inbound", "Cannot Quote"},
            {"SunLife Customer Referral", "Cannot Quote"},
            {"Swinton Hotkeys", "Cannot Quote"},
            {"Trafix Media ", "Cannot Quote"},
            {"VeroCover", "Cannot Quote"},
            {"Visionary Markets", "Cannot Quote"},
            {"Visionary Markets Sat", "Cannot Quote"},
            {"Visionary Markets Sun", "Cannot Quote"},
            {"Visionary Markets Social", "Cannot Quote"},
            {"Apply Online", "Sold"},
            {"Apply Online Sat", "Sold"},
            {"Apply Online Sun", "Sold"},
            {"Apply Online INCOMPLETE", "Sold"},
            {"Apply Online INCOMPLETE Sat", "Sold"},
            {"Apply Online INCOMPLETE Sun", "Sold"},
            {"Aspect Webmedia", "Sold"},
            {"Aspect Webmedia Sat", "Sold"},
            {"Aspect Webmedia Sun", "Sold"},
            {"Best Health Policy RA", "Sold"},
            {"Best Health Policy RA Sat", "Sold"},
            {"Best Health Policy RA Sun", "Sold"},
            {"Cavendish", "Sold"},
            {"Cavendish Dec", "Sold"},
            {"Cavendish Dec - DNC", "Sold"},
            {"Cavendish Dec - Hotkey", "Sold"},
            {"Cavendish - DNC", "Sold"},
            {"Cavendish Dec Customer Referral", "Sold"},
            {"Cavendish - Hotkey", "Sold"},
            {"Cavendish Customer Referral", "Sold"},
            {"clixel", "Sold"},
            {"CompareLife", "Sold"},
            {"clixel RA", "Sold"},
            {"Conectia", "Sold"},
            {"Deal Direct FS", "Sold"},
            {"DST Team", "Sold"},
            {"Dove Insurance", "Sold"},
            {"e-Finity", "Sold"},
            {"Engaged Solutions", "Sold"},
            {"eHealthCompare RA", "Sold"},
            {"eHealthCompare RA Sat", "Sold"},
            {"eHealthCompare RA Sun", "Sold"},
            {"eprospects", "Sold"},
            {"eprospect SAT", "Sold"},
            {"eprospect SUN", "Sold"},
            {"Esmart", "Sold"},
            {"Esmart Sat", "Sold"},
            {"Esmart Sun", "Sold"},
            {"finance_leads_online", "Sold"},
            {"50PlusLife.co.uk", "Sold"},
            {"Google", "Sold"},
            {"Hotkey(Internal)", "Sold"},
            {"HotKey Lead", "Sold"},
            {"Hotkey(Cavendish)", "Sold"},
            {"Hotkey(SunLife FLI)", "Sold"},
            {"Hotkey(SunLife GOF)", "Sold"},
            {"Impressia", "Sold"},
            {"internal", "Sold"},
            {"Kamicom", "Sold"},
            {"leadbay", "Sold"},
            {"LeadStream", "Sold"},
            {"LeadStream Sat", "Sold"},
            {"LeadStream Sun", "Sold"},
            {"Look For Health RA", "Sold"},
            {"Look For Health RA Sat", "Sold"},
            {"Look For Health RA Sun", "Sold"},
            {"look_for_life", "Sold"},
            {"Look For Life RA", "Sold"},
            {"Look For Life RA SAT", "Sold"},
            {"Look For Life RA SUN", "Sold"},
            {"LOANS REFERRAL", "Sold"},
            {"leadstream", "Sold"},
            {"leadstream Sat", "Sold"},
            {"leadstream Sun", "Sold"},
            {"livesure", "Sold"},
            {"Livesure RA", "Sold"},
            {"Livesure RA SAT", "Sold"},
            {"Livesure RA SUN", "Sold"},
            {"michael_anthony", "Sold"},
            {"michael_anthony SAT", "Sold"},
            {"michael_anthony SUN", "Sold"},
            {"michael_anthony ADD", "Sold"},
            {"MA WOL", "Sold"},
            {"MA WOL Sat", "Sold"},
            {"MA WOL Sun", "Sold"},
            {"MA WOL ADD", "Sold"},
            {"MA Switch", "Sold"},
            {"MA Switch Sat", "Sold"},
            {"MA Switch Sun", "Sold"},
            {"michael_anthony COMM", "Sold"},
            {"michael_anthony COMM SAT", "Sold"},
            {"michael_anthony COMM SUN", "Sold"},
            {"Baby Hotkey", "Sold"},
            {"Business Leads", "Sold"},
            {"BTQ Hotkey", "Sold"},
            {"BuyLife", "Sold"},
            {"First to Market", "Sold"},
            {"MA Inbound", "Sold"},
            {"Niche Data", "Sold"},
            {"Niche Hot Key", "Sold"},
            {"OSL", "Sold"},
            {"www.protected.co.uk", "Sold"},
            {"re-assured.co.uk", "Sold"},
            {"Customer Referral", "Sold"},
            {"SYN", "Sold"},
            {"melodi", "Sold"},
            {"Openwork", "Sold"},
            {"Protect4Life", "Sold"},
            {"premier_leads", "Sold"},
            {"premier_leads Sat", "Sold"},
            {"premier_leads Sun", "Sold"},
            {"PMI Advisor Callback", "Sold"},
            {"PMI Advisor Callback Sat", "Sold"},
            {"PMI Advisor Callback Sun", "Sold"},
            {"PMI Advisor Full Lead", "Sold"},
            {"PMI Advisor Full Lead Sat", "Sold"},
            {"PMI Advisor Full Lead Sun", "Sold"},
            {"PMI Pre CRM", "Sold"},
            {"Polly.co.uk", "Sold"},
            {"Polly.co.uk Sat", "Sold"},
            {"Polly.co.uk Sun", "Sold"},
            {"Provident", "Sold"},
            {"Quote Me Now", "Sold"},
            {"QSM Incentivised", "Sold"},
            {"QSM NotIncentivised", "Sold"},
            {"Quote Searcher", "Sold"},
            {"Quintessential", "Sold"},
            {"Quintessential Sat", "Sold"},
            {"Quintessential Sun", "Sold"},
            {"Reassured Archive S", "Sold"},
            {"Reassured Archive J", "Sold"},
            {"Reassured Health", "Sold"},
            {"Reassured Life", "Sold"},
            {"RA Email SurePolicy", "Sold"},
            {"RA Email SurePolicy SAT", "Sold"},
            {"RA Email SurePolicy SUN", "Sold"},
            {"RA PPC SureLoan", "Sold"},
            {"RA PPC SureLoan Sat", "Sold"},
            {"RA PPC SureLoan Sun", "Sold"},
            {"RA PPC SurePolicy", "Sold"},
            {"RA PPC SurePolicy SAT", "Sold"},
            {"RA PPC SurePolicy SUN", "Sold"},
            {"PMI Referral", "Sold"},
            {"PMI Client", "Sold"},
            {"Reassured Marketing", "Sold"},
            {"Reassured Marketing Sat", "Sold"},
            {"Reassured Marketing Sun", "Sold"},
            {"Reassured Marketing PMI", "Sold"},
            {"Reassured Marketing PMI SAT", "Sold"},
            {"Reassured Marketing PMI SUN", "Sold"},
            {"Reassured Marketing PPC", "Sold"},
            {"RA Shared Lead", "Sold"},
            {"RA Website", "Sold"},
            {"RA Website PMI", "Sold"},
            {"SunLife", "Sold"},
            {"SunLife Mature", "Sold"},
            {"SunLife Declined", "Sold"},
            {"SunLife - 45 day Expired", "Sold"},
            {"Sunlife GOF Capped", "Sold"},
            {"Sunlife GOF Capped DNC", "Sold"},
            {"Sunlife GOF", "Sold"},
            {"Sunlife GOF DNC", "Sold"},
            {"Sunlife GOF Customer Referral", "Sold"},
            {"Sunlife GOF(FLI)", "Sold"},
            {"Sunlife GOF (FLI) DNC", "Sold"},
            {"Sunlife GOF Expired", "Sold"},
            {"SunLife Hotkeys", "Sold"},
            {"SunLife Inbound", "Sold"},
            {"SunLife Customer Referral", "Sold"},
            {"Swinton Hotkeys", "Sold"},
            {"Trafix Media ", "Sold"},
            {"VeroCover", "Sold"},
            {"Visionary Markets", "Sold"},
            {"Visionary Markets Sat", "Sold"},
            {"Visionary Markets Sun", "Sold"},
            {"Visionary Markets Social", "Sold"}
    };
}
