package TestPrep;

/**
 * Created by hfletcher on 19/06/2018.
 */
public class AllLeadProvidersOne {

    public static String[][] AllLeadProviders = new String[][]{
            {"Apply Online", "Not Contacted"},
            {"Apply Online Sat", "Not Contacted"},
            {"Apply Online Sun", "Not Contacted"},
            {"Apply Online INCOMPLETE", "Not Contacted"},
            {"Apply Online INCOMPLETE Sat", "Not Contacted"},
            {"Apply Online INCOMPLETE Sun", "Not Contacted"},
            {"Aspect Webmedia", "Not Contacted"},
            {"Aspect Webmedia Sat", "Not Contacted"},
            {"Aspect Webmedia Sun", "Not Contacted"},
            {"Best Health Policy RA", "Not Contacted"},
            {"Best Health Policy RA Sat", "Not Contacted"},
            {"Best Health Policy RA Sun", "Not Contacted"},
            {"Cavendish", "Not Contacted"},
            {"Cavendish Dec", "Not Contacted"},
            {"Cavendish Dec - DNC", "Not Contacted"},
            {"Cavendish Dec - Hotkey", "Not Contacted"},
            {"Cavendish - DNC", "Not Contacted"},
            {"Cavendish Dec Customer Referral", "Not Contacted"},
            {"Cavendish - Hotkey", "Not Contacted"},
            {"Cavendish Customer Referral", "Not Contacted"},
            {"clixel", "Not Contacted"},
            {"CompareLife", "Not Contacted"},
            {"clixel RA", "Not Contacted"},
            {"Conectia", "Not Contacted"},
            {"Deal Direct FS", "Not Contacted"},
            {"DST Team", "Not Contacted"},
            {"Dove Insurance", "Not Contacted"},
            {"e-Finity", "Not Contacted"},
            {"Engaged Solutions", "Not Contacted"},
            {"eHealthCompare RA", "Not Contacted"},
            {"eHealthCompare RA Sat", "Not Contacted"},
            {"eHealthCompare RA Sun", "Not Contacted"},
            {"eprospects", "Not Contacted"},
            {"eprospect SAT", "Not Contacted"},
            {"eprospect SUN", "Not Contacted"},
            {"Esmart", "Not Contacted"},
            {"Esmart Sat", "Not Contacted"},
            {"Esmart Sun", "Not Contacted"},
            {"finance_leads_online", "Not Contacted"},
            {"50PlusLife.co.uk", "Not Contacted"},
            {"Google", "Not Contacted"},
            {"Hotkey(Internal)", "Not Contacted"},
            {"HotKey Lead", "Not Contacted"},
            {"Hotkey(Cavendish)", "Not Contacted"},
            {"Hotkey(SunLife FLI)", "Not Contacted"},
            {"Hotkey(SunLife GOF)", "Not Contacted"},
            {"Impressia", "Not Contacted"},
            {"internal", "Not Contacted"},
            {"Kamicom", "Not Contacted"},
            {"leadbay", "Not Contacted"},
            {"LeadStream", "Not Contacted"},
            {"LeadStream Sat", "Not Contacted"},
            {"LeadStream Sun", "Not Contacted"},
            {"Look For Health RA", "Not Contacted"},
            {"Look For Health RA Sat", "Not Contacted"},
            {"Look For Health RA Sun", "Not Contacted"},
            {"look_for_life", "Not Contacted"},
            {"Look For Life RA", "Not Contacted"},
            {"Look For Life RA SAT", "Not Contacted"},
            {"Look For Life RA SUN", "Not Contacted"},
            {"LOANS REFERRAL", "Not Contacted"},
            {"leadstream", "Not Contacted"},
            {"leadstream Sat", "Not Contacted"},
            {"leadstream Sun", "Not Contacted"},
            {"livesure", "Not Contacted"},
            {"Livesure RA", "Not Contacted"},
            {"Livesure RA SAT", "Not Contacted"},
            {"Livesure RA SUN", "Not Contacted"},
            {"michael_anthony", "Not Contacted"},
            {"michael_anthony SAT", "Not Contacted"},
            {"michael_anthony SUN", "Not Contacted"},
            {"michael_anthony ADD", "Not Contacted"},
            {"MA WOL", "Not Contacted"},
            {"MA WOL Sat", "Not Contacted"},
            {"MA WOL Sun", "Not Contacted"},
            {"MA WOL ADD", "Not Contacted"},
            {"MA Switch", "Not Contacted"},
            {"MA Switch Sat", "Not Contacted"},
            {"MA Switch Sun", "Not Contacted"},
            {"michael_anthony COMM", "Not Contacted"},
            {"michael_anthony COMM SAT", "Not Contacted"},
            {"michael_anthony COMM SUN", "Not Contacted"},
            {"Baby Hotkey", "Not Contacted"},
            {"Business Leads", "Not Contacted"},
            {"BTQ Hotkey", "Not Contacted"},
            {"BuyLife", "Not Contacted"},
            {"First to Market", "Not Contacted"},
            {"MA Inbound", "Not Contacted"},
            {"Niche Data", "Not Contacted"},
            {"Niche Hot Key", "Not Contacted"},
            {"OSL", "Not Contacted"},
            {"www.protected.co.uk", "Not Contacted"},
            {"re-assured.co.uk", "Not Contacted"},
            {"Customer Referral", "Not Contacted"},
            {"SYN", "Not Contacted"},
            {"melodi", "Not Contacted"},
            {"Openwork", "Not Contacted"},
            {"Protect4Life", "Not Contacted"},
            {"premier_leads", "Not Contacted"},
            {"premier_leads Sat", "Not Contacted"},
            {"premier_leads Sun", "Not Contacted"},
            {"PMI Advisor Callback", "Not Contacted"},
            {"PMI Advisor Callback Sat", "Not Contacted"},
            {"PMI Advisor Callback Sun", "Not Contacted"},
            {"PMI Advisor Full Lead", "Not Contacted"},
            {"PMI Advisor Full Lead Sat", "Not Contacted"},
            {"PMI Advisor Full Lead Sun", "Not Contacted"},
            {"PMI Pre CRM", "Not Contacted"},
            {"Polly.co.uk", "Not Contacted"},
            {"Polly.co.uk Sat", "Not Contacted"},
            {"Polly.co.uk Sun", "Not Contacted"},
            {"Provident", "Not Contacted"},
            {"Quote Me Now", "Not Contacted"},
            {"QSM Incentivised", "Not Contacted"},
            {"QSM NotIncentivised", "Not Contacted"},
            {"Quote Searcher", "Not Contacted"},
            {"Quintessential", "Not Contacted"},
            {"Quintessential Sat", "Not Contacted"},
            {"Quintessential Sun", "Not Contacted"},
            {"Reassured Archive S", "Not Contacted"},
            {"Reassured Archive J", "Not Contacted"},
            {"Reassured Health", "Not Contacted"},
            {"Reassured Life", "Not Contacted"},
            {"RA Email SurePolicy", "Not Contacted"},
            {"RA Email SurePolicy SAT", "Not Contacted"},
            {"RA Email SurePolicy SUN", "Not Contacted"},
            {"RA PPC SureLoan", "Not Contacted"},
            {"RA PPC SureLoan Sat", "Not Contacted"},
            {"RA PPC SureLoan Sun", "Not Contacted"},
            {"RA PPC SurePolicy", "Not Contacted"},
            {"RA PPC SurePolicy SAT", "Not Contacted"},
            {"RA PPC SurePolicy SUN", "Not Contacted"},
            {"PMI Referral", "Not Contacted"},
            {"PMI Client", "Not Contacted"},
            {"Reassured Marketing", "Not Contacted"},
            {"Reassured Marketing Sat", "Not Contacted"},
            {"Reassured Marketing Sun", "Not Contacted"},
            {"Reassured Marketing PMI", "Not Contacted"},
            {"Reassured Marketing PMI SAT", "Not Contacted"},
            {"Reassured Marketing PMI SUN", "Not Contacted"},
            {"Reassured Marketing PPC", "Not Contacted"},
            {"RA Shared Lead", "Not Contacted"},
            {"RA Website", "Not Contacted"},
            {"RA Website PMI", "Not Contacted"},
            {"SunLife", "Not Contacted"},
            {"SunLife Mature", "Not Contacted"},
            {"SunLife Declined", "Not Contacted"},
            {"SunLife - 45 day Expired", "Not Contacted"},
            {"Sunlife GOF Capped", "Not Contacted"},
            {"Sunlife GOF Capped DNC", "Not Contacted"},
            {"Sunlife GOF", "Not Contacted"},
            {"Sunlife GOF DNC", "Not Contacted"},
            {"Sunlife GOF Customer Referral", "Not Contacted"},
            {"Sunlife GOF(FLI)", "Not Contacted"},
            {"Sunlife GOF (FLI) DNC", "Not Contacted"},
            {"Sunlife GOF Expired", "Not Contacted"},
            {"SunLife Hotkeys", "Not Contacted"},
            {"SunLife Inbound", "Not Contacted"},
            {"SunLife Customer Referral", "Not Contacted"},
            {"Swinton Hotkeys", "Not Contacted"},
            {"Trafix Media ", "Not Contacted"},
            {"VeroCover", "Not Contacted"},
            {"Visionary Markets", "Not Contacted"},
            {"Visionary Markets Sat", "Not Contacted"},
            {"Visionary Markets Sun", "Not Contacted"},
            {"Visionary Markets Social", "Not Contacted"},
            {"Apply Online", "Contacted"},
            {"Apply Online Sat", "Contacted"},
            {"Apply Online Sun", "Contacted"},
            {"Apply Online INCOMPLETE", "Contacted"},
            {"Apply Online INCOMPLETE Sat", "Contacted"},
            {"Apply Online INCOMPLETE Sun", "Contacted"},
            {"Aspect Webmedia", "Contacted"},
            {"Aspect Webmedia Sat", "Contacted"},
            {"Aspect Webmedia Sun", "Contacted"},
            {"Best Health Policy RA", "Contacted"},
            {"Best Health Policy RA Sat", "Contacted"},
            {"Best Health Policy RA Sun", "Contacted"},
            {"Cavendish", "Contacted"},
            {"Cavendish Dec", "Contacted"},
            {"Cavendish Dec - DNC", "Contacted"},
            {"Cavendish Dec - Hotkey", "Contacted"},
            {"Cavendish - DNC", "Contacted"},
            {"Cavendish Dec Customer Referral", "Contacted"},
            {"Cavendish - Hotkey", "Contacted"},
            {"Cavendish Customer Referral", "Contacted"},
            {"clixel", "Contacted"},
            {"CompareLife", "Contacted"},
            {"clixel RA", "Contacted"},
            {"Conectia", "Contacted"},
            {"Deal Direct FS", "Contacted"},
            {"DST Team", "Contacted"},
            {"Dove Insurance", "Contacted"},
            {"e-Finity", "Contacted"},
            {"Engaged Solutions", "Contacted"},
            {"eHealthCompare RA", "Contacted"},
            {"eHealthCompare RA Sat", "Contacted"},
            {"eHealthCompare RA Sun", "Contacted"},
            {"eprospects", "Contacted"},
            {"eprospect SAT", "Contacted"},
            {"eprospect SUN", "Contacted"},
            {"Esmart", "Contacted"},
            {"Esmart Sat", "Contacted"},
            {"Esmart Sun", "Contacted"},
            {"finance_leads_online", "Contacted"},
            {"50PlusLife.co.uk", "Contacted"},
            {"Google", "Contacted"},
            {"Hotkey(Internal)", "Contacted"},
            {"HotKey Lead", "Contacted"},
            {"Hotkey(Cavendish)", "Contacted"},
            {"Hotkey(SunLife FLI)", "Contacted"},
            {"Hotkey(SunLife GOF)", "Contacted"},
            {"Impressia", "Contacted"},
            {"internal", "Contacted"},
            {"Kamicom", "Contacted"},
            {"leadbay", "Contacted"},
            {"LeadStream", "Contacted"},
            {"LeadStream Sat", "Contacted"},
            {"LeadStream Sun", "Contacted"},
            {"Look For Health RA", "Contacted"},
            {"Look For Health RA Sat", "Contacted"},
            {"Look For Health RA Sun", "Contacted"},
            {"look_for_life", "Contacted"},
            {"Look For Life RA", "Contacted"},
            {"Look For Life RA SAT", "Contacted"},
            {"Look For Life RA SUN", "Contacted"},
            {"LOANS REFERRAL", "Contacted"},
            {"leadstream", "Contacted"},
            {"leadstream Sat", "Contacted"},
            {"leadstream Sun", "Contacted"},
            {"livesure", "Contacted"},
            {"Livesure RA", "Contacted"},
            {"Livesure RA SAT", "Contacted"},
            {"Livesure RA SUN", "Contacted"},
            {"michael_anthony", "Contacted"},
            {"michael_anthony SAT", "Contacted"},
            {"michael_anthony SUN", "Contacted"},
            {"michael_anthony ADD", "Contacted"},
            {"MA WOL", "Contacted"},
            {"MA WOL Sat", "Contacted"},
            {"MA WOL Sun", "Contacted"},
            {"MA WOL ADD", "Contacted"},
            {"MA Switch", "Contacted"},
            {"MA Switch Sat", "Contacted"},
            {"MA Switch Sun", "Contacted"},
            {"michael_anthony COMM", "Contacted"},
            {"michael_anthony COMM SAT", "Contacted"},
            {"michael_anthony COMM SUN", "Contacted"},
            {"Baby Hotkey", "Contacted"},
            {"Business Leads", "Contacted"},
            {"BTQ Hotkey", "Contacted"},
            {"BuyLife", "Contacted"},
            {"First to Market", "Contacted"},
            {"MA Inbound", "Contacted"},
            {"Niche Data", "Contacted"},
            {"Niche Hot Key", "Contacted"},
            {"OSL", "Contacted"},
            {"www.protected.co.uk", "Contacted"},
            {"re-assured.co.uk", "Contacted"},
            {"Customer Referral", "Contacted"},
            {"SYN", "Contacted"},
            {"melodi", "Contacted"},
            {"Openwork", "Contacted"},
            {"Protect4Life", "Contacted"},
            {"premier_leads", "Contacted"},
            {"premier_leads Sat", "Contacted"},
            {"premier_leads Sun", "Contacted"},
            {"PMI Advisor Callback", "Contacted"},
            {"PMI Advisor Callback Sat", "Contacted"},
            {"PMI Advisor Callback Sun", "Contacted"},
            {"PMI Advisor Full Lead", "Contacted"},
            {"PMI Advisor Full Lead Sat", "Contacted"},
            {"PMI Advisor Full Lead Sun", "Contacted"},
            {"PMI Pre CRM", "Contacted"},
            {"Polly.co.uk", "Contacted"},
            {"Polly.co.uk Sat", "Contacted"},
            {"Polly.co.uk Sun", "Contacted"},
            {"Provident", "Contacted"},
            {"Quote Me Now", "Contacted"},
            {"QSM Incentivised", "Contacted"},
            {"QSM NotIncentivised", "Contacted"},
            {"Quote Searcher", "Contacted"},
            {"Quintessential", "Contacted"},
            {"Quintessential Sat", "Contacted"},
            {"Quintessential Sun", "Contacted"},
            {"Reassured Archive S", "Contacted"},
            {"Reassured Archive J", "Contacted"},
            {"Reassured Health", "Contacted"},
            {"Reassured Life", "Contacted"},
            {"RA Email SurePolicy", "Contacted"},
            {"RA Email SurePolicy SAT", "Contacted"},
            {"RA Email SurePolicy SUN", "Contacted"},
            {"RA PPC SureLoan", "Contacted"},
            {"RA PPC SureLoan Sat", "Contacted"},
            {"RA PPC SureLoan Sun", "Contacted"},
            {"RA PPC SurePolicy", "Contacted"},
            {"RA PPC SurePolicy SAT", "Contacted"},
            {"RA PPC SurePolicy SUN", "Contacted"},
            {"PMI Referral", "Contacted"},
            {"PMI Client", "Contacted"},
            {"Reassured Marketing", "Contacted"},
            {"Reassured Marketing Sat", "Contacted"},
            {"Reassured Marketing Sun", "Contacted"},
            {"Reassured Marketing PMI", "Contacted"},
            {"Reassured Marketing PMI SAT", "Contacted"},
            {"Reassured Marketing PMI SUN", "Contacted"},
            {"Reassured Marketing PPC", "Contacted"},
            {"RA Shared Lead", "Contacted"},
            {"RA Website", "Contacted"},
            {"RA Website PMI", "Contacted"},
            {"SunLife", "Contacted"},
            {"SunLife Mature", "Contacted"},
            {"SunLife Declined", "Contacted"},
            {"SunLife - 45 day Expired", "Contacted"},
            {"Sunlife GOF Capped", "Contacted"},
            {"Sunlife GOF Capped DNC", "Contacted"},
            {"Sunlife GOF", "Contacted"},
            {"Sunlife GOF DNC", "Contacted"},
            {"Sunlife GOF Customer Referral", "Contacted"},
            {"Sunlife GOF(FLI)", "Contacted"},
            {"Sunlife GOF (FLI) DNC", "Contacted"},
            {"Sunlife GOF Expired", "Contacted"},
            {"SunLife Hotkeys", "Contacted"},
            {"SunLife Inbound", "Contacted"},
            {"SunLife Customer Referral", "Contacted"},
            {"Swinton Hotkeys", "Contacted"},
            {"Trafix Media ", "Contacted"},
            {"VeroCover", "Contacted"},
            {"Visionary Markets", "Contacted"},
            {"Visionary Markets Sat", "Contacted"},
            {"Visionary Markets Sun", "Contacted"},
            {"Visionary Markets Social", "Contacted"}
    };
}
