package TestPrep;

/**
 * Created by hfletcher on 19/06/2018.
 */
public class AllLeadProvidersFour {

    public static String[][] AllLeadProviders = new String[][]{

            {"Apply Online", "Chicken Wings"},
            {"Apply Online Sat", "Chicken Wings"},
            {"Apply Online Sun", "Chicken Wings"},
            {"Apply Online INCOMPLETE", "Chicken Wings"},
            {"Apply Online INCOMPLETE Sat", "Chicken Wings"},
            {"Apply Online INCOMPLETE Sun", "Chicken Wings"},
            {"Aspect Webmedia", "Chicken Wings"},
            {"Aspect Webmedia Sat", "Chicken Wings"},
            {"Aspect Webmedia Sun", "Chicken Wings"},
            {"Best Health Policy RA", "Chicken Wings"},
            {"Best Health Policy RA Sat", "Chicken Wings"},
            {"Best Health Policy RA Sun", "Chicken Wings"},
            {"Cavendish", "Chicken Wings"},
            {"Cavendish Dec", "Chicken Wings"},
            {"Cavendish Dec - DNC", "Chicken Wings"},
            {"Cavendish Dec - Hotkey", "Chicken Wings"},
            {"Cavendish - DNC", "Chicken Wings"},
            {"Cavendish Dec Customer Referral", "Chicken Wings"},
            {"Cavendish - Hotkey", "Chicken Wings"},
            {"Cavendish Customer Referral", "Chicken Wings"},
            {"clixel", "Chicken Wings"},
            {"CompareLife", "Chicken Wings"},
            {"clixel RA", "Chicken Wings"},
            {"Conectia", "Chicken Wings"},
            {"Deal Direct FS", "Chicken Wings"},
            {"DST Team", "Chicken Wings"},
            {"Dove Insurance", "Chicken Wings"},
            {"e-Finity", "Chicken Wings"},
            {"Engaged Solutions", "Chicken Wings"},
            {"eHealthCompare RA", "Chicken Wings"},
            {"eHealthCompare RA Sat", "Chicken Wings"},
            {"eHealthCompare RA Sun", "Chicken Wings"},
            {"eprospects", "Chicken Wings"},
            {"eprospect SAT", "Chicken Wings"},
            {"eprospect SUN", "Chicken Wings"},
            {"Esmart", "Chicken Wings"},
            {"Esmart Sat", "Chicken Wings"},
            {"Esmart Sun", "Chicken Wings"},
            {"finance_leads_online", "Chicken Wings"},
            {"50PlusLife.co.uk", "Chicken Wings"},
            {"Google", "Chicken Wings"},
            {"Hotkey(Internal)", "Chicken Wings"},
            {"HotKey Lead", "Chicken Wings"},
            {"Hotkey(Cavendish)", "Chicken Wings"},
            {"Hotkey(SunLife FLI)", "Chicken Wings"},
            {"Hotkey(SunLife GOF)", "Chicken Wings"},
            {"Impressia", "Chicken Wings"},
            {"internal", "Chicken Wings"},
            {"Kamicom", "Chicken Wings"},
            {"leadbay", "Chicken Wings"},
            {"LeadStream", "Chicken Wings"},
            {"LeadStream Sat", "Chicken Wings"},
            {"LeadStream Sun", "Chicken Wings"},
            {"Look For Health RA", "Chicken Wings"},
            {"Look For Health RA Sat", "Chicken Wings"},
            {"Look For Health RA Sun", "Chicken Wings"},
            {"look_for_life", "Chicken Wings"},
            {"Look For Life RA", "Chicken Wings"},
            {"Look For Life RA SAT", "Chicken Wings"},
            {"Look For Life RA SUN", "Chicken Wings"},
            {"LOANS REFERRAL", "Chicken Wings"},
            {"leadstream", "Chicken Wings"},
            {"leadstream Sat", "Chicken Wings"},
            {"leadstream Sun", "Chicken Wings"},
            {"livesure", "Chicken Wings"},
            {"Livesure RA", "Chicken Wings"},
            {"Livesure RA SAT", "Chicken Wings"},
            {"Livesure RA SUN", "Chicken Wings"},
            {"michael_anthony", "Chicken Wings"},
            {"michael_anthony SAT", "Chicken Wings"},
            {"michael_anthony SUN", "Chicken Wings"},
            {"michael_anthony ADD", "Chicken Wings"},
            {"MA WOL", "Chicken Wings"},
            {"MA WOL Sat", "Chicken Wings"},
            {"MA WOL Sun", "Chicken Wings"},
            {"MA WOL ADD", "Chicken Wings"},
            {"MA Switch", "Chicken Wings"},
            {"MA Switch Sat", "Chicken Wings"},
            {"MA Switch Sun", "Chicken Wings"},
            {"michael_anthony COMM", "Chicken Wings"},
            {"michael_anthony COMM SAT", "Chicken Wings"},
            {"michael_anthony COMM SUN", "Chicken Wings"},
            {"Baby Hotkey", "Chicken Wings"},
            {"Business Leads", "Chicken Wings"},
            {"BTQ Hotkey", "Chicken Wings"},
            {"BuyLife", "Chicken Wings"},
            {"First to Market", "Chicken Wings"},
            {"MA Inbound", "Chicken Wings"},
            {"Niche Data", "Chicken Wings"},
            {"Niche Hot Key", "Chicken Wings"},
            {"OSL", "Chicken Wings"},
            {"www.protected.co.uk", "Chicken Wings"},
            {"re-assured.co.uk", "Chicken Wings"},
            {"Customer Referral", "Chicken Wings"},
            {"SYN", "Chicken Wings"},
            {"melodi", "Chicken Wings"},
            {"Openwork", "Chicken Wings"},
            {"Protect4Life", "Chicken Wings"},
            {"premier_leads", "Chicken Wings"},
            {"premier_leads Sat", "Chicken Wings"},
            {"premier_leads Sun", "Chicken Wings"},
            {"PMI Advisor Callback", "Chicken Wings"},
            {"PMI Advisor Callback Sat", "Chicken Wings"},
            {"PMI Advisor Callback Sun", "Chicken Wings"},
            {"PMI Advisor Full Lead", "Chicken Wings"},
            {"PMI Advisor Full Lead Sat", "Chicken Wings"},
            {"PMI Advisor Full Lead Sun", "Chicken Wings"},
            {"PMI Pre CRM", "Chicken Wings"},
            {"Polly.co.uk", "Chicken Wings"},
            {"Polly.co.uk Sat", "Chicken Wings"},
            {"Polly.co.uk Sun", "Chicken Wings"},
            {"Provident", "Chicken Wings"},
            {"Quote Me Now", "Chicken Wings"},
            {"QSM Incentivised", "Chicken Wings"},
            {"QSM NotIncentivised", "Chicken Wings"},
            {"Quote Searcher", "Chicken Wings"},
            {"Quintessential", "Chicken Wings"},
            {"Quintessential Sat", "Chicken Wings"},
            {"Quintessential Sun", "Chicken Wings"},
            {"Reassured Archive S", "Chicken Wings"},
            {"Reassured Archive J", "Chicken Wings"},
            {"Reassured Health", "Chicken Wings"},
            {"Reassured Life", "Chicken Wings"},
            {"RA Email SurePolicy", "Chicken Wings"},
            {"RA Email SurePolicy SAT", "Chicken Wings"},
            {"RA Email SurePolicy SUN", "Chicken Wings"},
            {"RA PPC SureLoan", "Chicken Wings"},
            {"RA PPC SureLoan Sat", "Chicken Wings"},
            {"RA PPC SureLoan Sun", "Chicken Wings"},
            {"RA PPC SurePolicy", "Chicken Wings"},
            {"RA PPC SurePolicy SAT", "Chicken Wings"},
            {"RA PPC SurePolicy SUN", "Chicken Wings"},
            {"PMI Referral", "Chicken Wings"},
            {"PMI Client", "Chicken Wings"},
            {"Reassured Marketing", "Chicken Wings"},
            {"Reassured Marketing Sat", "Chicken Wings"},
            {"Reassured Marketing Sun", "Chicken Wings"},
            {"Reassured Marketing PMI", "Chicken Wings"},
            {"Reassured Marketing PMI SAT", "Chicken Wings"},
            {"Reassured Marketing PMI SUN", "Chicken Wings"},
            {"Reassured Marketing PPC", "Chicken Wings"},
            {"RA Shared Lead", "Chicken Wings"},
            {"RA Website", "Chicken Wings"},
            {"RA Website PMI", "Chicken Wings"},
            {"SunLife", "Chicken Wings"},
            {"SunLife Mature", "Chicken Wings"},
            {"SunLife Declined", "Chicken Wings"},
            {"SunLife - 45 day Expired", "Chicken Wings"},
            {"Sunlife GOF Capped", "Chicken Wings"},
            {"Sunlife GOF Capped DNC", "Chicken Wings"},
            {"Sunlife GOF", "Chicken Wings"},
            {"Sunlife GOF DNC", "Chicken Wings"},
            {"Sunlife GOF Customer Referral", "Chicken Wings"},
            {"Sunlife GOF(FLI)", "Chicken Wings"},
            {"Sunlife GOF (FLI) DNC", "Chicken Wings"},
            {"Sunlife GOF Expired", "Chicken Wings"},
            {"SunLife Hotkeys", "Chicken Wings"},
            {"SunLife Inbound", "Chicken Wings"},
            {"SunLife Customer Referral", "Chicken Wings"},
            {"Swinton Hotkeys", "Chicken Wings"},
            {"Trafix Media ", "Chicken Wings"},
            {"VeroCover", "Chicken Wings"},
            {"Visionary Markets", "Chicken Wings"},
            {"Visionary Markets Sat", "Chicken Wings"},
            {"Visionary Markets Sun", "Chicken Wings"},
            {"Visionary Markets Social", "Chicken Wings"},
            {"Apply Online", "Assigned"},
            {"Apply Online Sat", "Assigned"},
            {"Apply Online Sun", "Assigned"},
            {"Apply Online INCOMPLETE", "Assigned"},
            {"Apply Online INCOMPLETE Sat", "Assigned"},
            {"Apply Online INCOMPLETE Sun", "Assigned"},
            {"Aspect Webmedia", "Assigned"},
            {"Aspect Webmedia Sat", "Assigned"},
            {"Aspect Webmedia Sun", "Assigned"},
            {"Best Health Policy RA", "Assigned"},
            {"Best Health Policy RA Sat", "Assigned"},
            {"Best Health Policy RA Sun", "Assigned"},
            {"Cavendish", "Assigned"},
            {"Cavendish Dec", "Assigned"},
            {"Cavendish Dec - DNC", "Assigned"},
            {"Cavendish Dec - Hotkey", "Assigned"},
            {"Cavendish - DNC", "Assigned"},
            {"Cavendish Dec Customer Referral", "Assigned"},
            {"Cavendish - Hotkey", "Assigned"},
            {"Cavendish Customer Referral", "Assigned"},
            {"clixel", "Assigned"},
            {"CompareLife", "Assigned"},
            {"clixel RA", "Assigned"},
            {"Conectia", "Assigned"},
            {"Deal Direct FS", "Assigned"},
            {"DST Team", "Assigned"},
            {"Dove Insurance", "Assigned"},
            {"e-Finity", "Assigned"},
            {"Engaged Solutions", "Assigned"},
            {"eHealthCompare RA", "Assigned"},
            {"eHealthCompare RA Sat", "Assigned"},
            {"eHealthCompare RA Sun", "Assigned"},
            {"eprospects", "Assigned"},
            {"eprospect SAT", "Assigned"},
            {"eprospect SUN", "Assigned"},
            {"Esmart", "Assigned"},
            {"Esmart Sat", "Assigned"},
            {"Esmart Sun", "Assigned"},
            {"finance_leads_online", "Assigned"},
            {"50PlusLife.co.uk", "Assigned"},
            {"Google", "Assigned"},
            {"Hotkey(Internal)", "Assigned"},
            {"HotKey Lead", "Assigned"},
            {"Hotkey(Cavendish)", "Assigned"},
            {"Hotkey(SunLife FLI)", "Assigned"},
            {"Hotkey(SunLife GOF)", "Assigned"},
            {"Impressia", "Assigned"},
            {"internal", "Assigned"},
            {"Kamicom", "Assigned"},
            {"leadbay", "Assigned"},
            {"LeadStream", "Assigned"},
            {"LeadStream Sat", "Assigned"},
            {"LeadStream Sun", "Assigned"},
            {"Look For Health RA", "Assigned"},
            {"Look For Health RA Sat", "Assigned"},
            {"Look For Health RA Sun", "Assigned"},
            {"look_for_life", "Assigned"},
            {"Look For Life RA", "Assigned"},
            {"Look For Life RA SAT", "Assigned"},
            {"Look For Life RA SUN", "Assigned"},
            {"LOANS REFERRAL", "Assigned"},
            {"leadstream", "Assigned"},
            {"leadstream Sat", "Assigned"},
            {"leadstream Sun", "Assigned"},
            {"livesure", "Assigned"},
            {"Livesure RA", "Assigned"},
            {"Livesure RA SAT", "Assigned"},
            {"Livesure RA SUN", "Assigned"},
            {"michael_anthony", "Assigned"},
            {"michael_anthony SAT", "Assigned"},
            {"michael_anthony SUN", "Assigned"},
            {"michael_anthony ADD", "Assigned"},
            {"MA WOL", "Assigned"},
            {"MA WOL Sat", "Assigned"},
            {"MA WOL Sun", "Assigned"},
            {"MA WOL ADD", "Assigned"},
            {"MA Switch", "Assigned"},
            {"MA Switch Sat", "Assigned"},
            {"MA Switch Sun", "Assigned"},
            {"michael_anthony COMM", "Assigned"},
            {"michael_anthony COMM SAT", "Assigned"},
            {"michael_anthony COMM SUN", "Assigned"},
            {"Baby Hotkey", "Assigned"},
            {"Business Leads", "Assigned"},
            {"BTQ Hotkey", "Assigned"},
            {"BuyLife", "Assigned"},
            {"First to Market", "Assigned"},
            {"MA Inbound", "Assigned"},
            {"Niche Data", "Assigned"},
            {"Niche Hot Key", "Assigned"},
            {"OSL", "Assigned"},
            {"www.protected.co.uk", "Assigned"},
            {"re-assured.co.uk", "Assigned"},
            {"Customer Referral", "Assigned"},
            {"SYN", "Assigned"},
            {"melodi", "Assigned"},
            {"Openwork", "Assigned"},
            {"Protect4Life", "Assigned"},
            {"premier_leads", "Assigned"},
            {"premier_leads Sat", "Assigned"},
            {"premier_leads Sun", "Assigned"},
            {"PMI Advisor Callback", "Assigned"},
            {"PMI Advisor Callback Sat", "Assigned"},
            {"PMI Advisor Callback Sun", "Assigned"},
            {"PMI Advisor Full Lead", "Assigned"},
            {"PMI Advisor Full Lead Sat", "Assigned"},
            {"PMI Advisor Full Lead Sun", "Assigned"},
            {"PMI Pre CRM", "Assigned"},
            {"Polly.co.uk", "Assigned"},
            {"Polly.co.uk Sat", "Assigned"},
            {"Polly.co.uk Sun", "Assigned"},
            {"Provident", "Assigned"},
            {"Quote Me Now", "Assigned"},
            {"QSM Incentivised", "Assigned"},
            {"QSM NotIncentivised", "Assigned"},
            {"Quote Searcher", "Assigned"},
            {"Quintessential", "Assigned"},
            {"Quintessential Sat", "Assigned"},
            {"Quintessential Sun", "Assigned"},
            {"Reassured Archive S", "Assigned"},
            {"Reassured Archive J", "Assigned"},
            {"Reassured Health", "Assigned"},
            {"Reassured Life", "Assigned"},
            {"RA Email SurePolicy", "Assigned"},
            {"RA Email SurePolicy SAT", "Assigned"},
            {"RA Email SurePolicy SUN", "Assigned"},
            {"RA PPC SureLoan", "Assigned"},
            {"RA PPC SureLoan Sat", "Assigned"},
            {"RA PPC SureLoan Sun", "Assigned"},
            {"RA PPC SurePolicy", "Assigned"},
            {"RA PPC SurePolicy SAT", "Assigned"},
            {"RA PPC SurePolicy SUN", "Assigned"},
            {"PMI Referral", "Assigned"},
            {"PMI Client", "Assigned"},
            {"Reassured Marketing", "Assigned"},
            {"Reassured Marketing Sat", "Assigned"},
            {"Reassured Marketing Sun", "Assigned"},
            {"Reassured Marketing PMI", "Assigned"},
            {"Reassured Marketing PMI SAT", "Assigned"},
            {"Reassured Marketing PMI SUN", "Assigned"},
            {"Reassured Marketing PPC", "Assigned"},
            {"RA Shared Lead", "Assigned"},
            {"RA Website", "Assigned"},
            {"RA Website PMI", "Assigned"},
            {"SunLife", "Assigned"},
            {"SunLife Mature", "Assigned"},
            {"SunLife Declined", "Assigned"},
            {"SunLife - 45 day Expired", "Assigned"},
            {"Sunlife GOF Capped", "Assigned"},
            {"Sunlife GOF Capped DNC", "Assigned"},
            {"Sunlife GOF", "Assigned"},
            {"Sunlife GOF DNC", "Assigned"},
            {"Sunlife GOF Customer Referral", "Assigned"},
            {"Sunlife GOF(FLI)", "Assigned"},
            {"Sunlife GOF (FLI) DNC", "Assigned"},
            {"Sunlife GOF Expired", "Assigned"},
            {"SunLife Hotkeys", "Assigned"},
            {"SunLife Inbound", "Assigned"},
            {"SunLife Customer Referral", "Assigned"},
            {"Swinton Hotkeys", "Assigned"},
            {"Trafix Media ", "Assigned"},
            {"VeroCover", "Assigned"},
            {"Visionary Markets", "Assigned"},
            {"Visionary Markets Sat", "Assigned"},
            {"Visionary Markets Sun", "Assigned"},
            {"Visionary Markets Social", "Assigned"},
            {"Apply Online", "Postponed"},
            {"Apply Online Sat", "Postponed"},
            {"Apply Online Sun", "Postponed"},
            {"Apply Online INCOMPLETE", "Postponed"},
            {"Apply Online INCOMPLETE Sat", "Postponed"},
            {"Apply Online INCOMPLETE Sun", "Postponed"},
            {"Aspect Webmedia", "Postponed"},
            {"Aspect Webmedia Sat", "Postponed"},
            {"Aspect Webmedia Sun", "Postponed"},
            {"Best Health Policy RA", "Postponed"},
            {"Best Health Policy RA Sat", "Postponed"},
            {"Best Health Policy RA Sun", "Postponed"},
            {"Cavendish", "Postponed"},
            {"Cavendish Dec", "Postponed"},
            {"Cavendish Dec - DNC", "Postponed"},
            {"Cavendish Dec - Hotkey", "Postponed"},
            {"Cavendish - DNC", "Postponed"},
            {"Cavendish Dec Customer Referral", "Postponed"},
            {"Cavendish - Hotkey", "Postponed"},
            {"Cavendish Customer Referral", "Postponed"},
            {"clixel", "Postponed"},
            {"CompareLife", "Postponed"},
            {"clixel RA", "Postponed"},
            {"Conectia", "Postponed"},
            {"Deal Direct FS", "Postponed"},
            {"DST Team", "Postponed"},
            {"Dove Insurance", "Postponed"},
            {"e-Finity", "Postponed"},
            {"Engaged Solutions", "Postponed"},
            {"eHealthCompare RA", "Postponed"},
            {"eHealthCompare RA Sat", "Postponed"},
            {"eHealthCompare RA Sun", "Postponed"},
            {"eprospects", "Postponed"},
            {"eprospect SAT", "Postponed"},
            {"eprospect SUN", "Postponed"},
            {"Esmart", "Postponed"},
            {"Esmart Sat", "Postponed"},
            {"Esmart Sun", "Postponed"},
            {"finance_leads_online", "Postponed"},
            {"50PlusLife.co.uk", "Postponed"},
            {"Google", "Postponed"},
            {"Hotkey(Internal)", "Postponed"},
            {"HotKey Lead", "Postponed"},
            {"Hotkey(Cavendish)", "Postponed"},
            {"Hotkey(SunLife FLI)", "Postponed"},
            {"Hotkey(SunLife GOF)", "Postponed"},
            {"Impressia", "Postponed"},
            {"internal", "Postponed"},
            {"Kamicom", "Postponed"},
            {"leadbay", "Postponed"},
            {"LeadStream", "Postponed"},
            {"LeadStream Sat", "Postponed"},
            {"LeadStream Sun", "Postponed"},
            {"Look For Health RA", "Postponed"},
            {"Look For Health RA Sat", "Postponed"},
            {"Look For Health RA Sun", "Postponed"},
            {"look_for_life", "Postponed"},
            {"Look For Life RA", "Postponed"},
            {"Look For Life RA SAT", "Postponed"},
            {"Look For Life RA SUN", "Postponed"},
            {"LOANS REFERRAL", "Postponed"},
            {"leadstream", "Postponed"},
            {"leadstream Sat", "Postponed"},
            {"leadstream Sun", "Postponed"},
            {"livesure", "Postponed"},
            {"Livesure RA", "Postponed"},
            {"Livesure RA SAT", "Postponed"},
            {"Livesure RA SUN", "Postponed"},
            {"michael_anthony", "Postponed"},
            {"michael_anthony SAT", "Postponed"},
            {"michael_anthony SUN", "Postponed"},
            {"michael_anthony ADD", "Postponed"},
            {"MA WOL", "Postponed"},
            {"MA WOL Sat", "Postponed"},
            {"MA WOL Sun", "Postponed"},
            {"MA WOL ADD", "Postponed"},
            {"MA Switch", "Postponed"},
            {"MA Switch Sat", "Postponed"},
            {"MA Switch Sun", "Postponed"},
            {"michael_anthony COMM", "Postponed"},
            {"michael_anthony COMM SAT", "Postponed"},
            {"michael_anthony COMM SUN", "Postponed"},
            {"Baby Hotkey", "Postponed"},
            {"Business Leads", "Postponed"},
            {"BTQ Hotkey", "Postponed"},
            {"BuyLife", "Postponed"},
            {"First to Market", "Postponed"},
            {"MA Inbound", "Postponed"},
            {"Niche Data", "Postponed"},
            {"Niche Hot Key", "Postponed"},
            {"OSL", "Postponed"},
            {"www.protected.co.uk", "Postponed"},
            {"re-assured.co.uk", "Postponed"},
            {"Customer Referral", "Postponed"},
            {"SYN", "Postponed"},
            {"melodi", "Postponed"},
            {"Openwork", "Postponed"},
            {"Protect4Life", "Postponed"},
            {"premier_leads", "Postponed"},
            {"premier_leads Sat", "Postponed"},
            {"premier_leads Sun", "Postponed"},
            {"PMI Advisor Callback", "Postponed"},
            {"PMI Advisor Callback Sat", "Postponed"},
            {"PMI Advisor Callback Sun", "Postponed"},
            {"PMI Advisor Full Lead", "Postponed"},
            {"PMI Advisor Full Lead Sat", "Postponed"},
            {"PMI Advisor Full Lead Sun", "Postponed"},
            {"PMI Pre CRM", "Postponed"},
            {"Polly.co.uk", "Postponed"},
            {"Polly.co.uk Sat", "Postponed"},
            {"Polly.co.uk Sun", "Postponed"},
            {"Provident", "Postponed"},
            {"Quote Me Now", "Postponed"},
            {"QSM Incentivised", "Postponed"},
            {"QSM NotIncentivised", "Postponed"},
            {"Quote Searcher", "Postponed"},
            {"Quintessential", "Postponed"},
            {"Quintessential Sat", "Postponed"},
            {"Quintessential Sun", "Postponed"},
            {"Reassured Archive S", "Postponed"},
            {"Reassured Archive J", "Postponed"},
            {"Reassured Health", "Postponed"},
            {"Reassured Life", "Postponed"},
            {"RA Email SurePolicy", "Postponed"},
            {"RA Email SurePolicy SAT", "Postponed"},
            {"RA Email SurePolicy SUN", "Postponed"},
            {"RA PPC SureLoan", "Postponed"},
            {"RA PPC SureLoan Sat", "Postponed"},
            {"RA PPC SureLoan Sun", "Postponed"},
            {"RA PPC SurePolicy", "Postponed"},
            {"RA PPC SurePolicy SAT", "Postponed"},
            {"RA PPC SurePolicy SUN", "Postponed"},
            {"PMI Referral", "Postponed"},
            {"PMI Client", "Postponed"},
            {"Reassured Marketing", "Postponed"},
            {"Reassured Marketing Sat", "Postponed"},
            {"Reassured Marketing Sun", "Postponed"},
            {"Reassured Marketing PMI", "Postponed"},
            {"Reassured Marketing PMI SAT", "Postponed"},
            {"Reassured Marketing PMI SUN", "Postponed"},
            {"Reassured Marketing PPC", "Postponed"},
            {"RA Shared Lead", "Postponed"},
            {"RA Website", "Postponed"},
            {"RA Website PMI", "Postponed"},
            {"SunLife", "Postponed"},
            {"SunLife Mature", "Postponed"},
            {"SunLife Declined", "Postponed"},
            {"SunLife - 45 day Expired", "Postponed"},
            {"Sunlife GOF Capped", "Postponed"},
            {"Sunlife GOF Capped DNC", "Postponed"},
            {"Sunlife GOF", "Postponed"},
            {"Sunlife GOF DNC", "Postponed"},
            {"Sunlife GOF Customer Referral", "Postponed"},
            {"Sunlife GOF(FLI)", "Postponed"},
            {"Sunlife GOF (FLI) DNC", "Postponed"},
            {"Sunlife GOF Expired", "Postponed"},
            {"SunLife Hotkeys", "Postponed"},
            {"SunLife Inbound", "Postponed"},
            {"SunLife Customer Referral", "Postponed"},
            {"Swinton Hotkeys", "Postponed"},
            {"Trafix Media ", "Postponed"},
            {"VeroCover", "Postponed"},
            {"Visionary Markets", "Postponed"},
            {"Visionary Markets Sat", "Postponed"},
            {"Visionary Markets Sun", "Postponed"},
            {"Visionary Markets Social", "Postponed"},
            {"Apply Online", "Declined"},
            {"Apply Online Sat", "Declined"},
            {"Apply Online Sun", "Declined"},
            {"Apply Online INCOMPLETE", "Declined"},
            {"Apply Online INCOMPLETE Sat", "Declined"},
            {"Apply Online INCOMPLETE Sun", "Declined"},
            {"Aspect Webmedia", "Declined"},
            {"Aspect Webmedia Sat", "Declined"},
            {"Aspect Webmedia Sun", "Declined"},
            {"Best Health Policy RA", "Declined"},
            {"Best Health Policy RA Sat", "Declined"},
            {"Best Health Policy RA Sun", "Declined"},
            {"Cavendish", "Declined"},
            {"Cavendish Dec", "Declined"},
            {"Cavendish Dec - DNC", "Declined"},
            {"Cavendish Dec - Hotkey", "Declined"},
            {"Cavendish - DNC", "Declined"},
            {"Cavendish Dec Customer Referral", "Declined"},
            {"Cavendish - Hotkey", "Declined"},
            {"Cavendish Customer Referral", "Declined"},
            {"clixel", "Declined"},
            {"CompareLife", "Declined"},
            {"clixel RA", "Declined"},
            {"Conectia", "Declined"},
            {"Deal Direct FS", "Declined"},
            {"DST Team", "Declined"},
            {"Dove Insurance", "Declined"},
            {"e-Finity", "Declined"},
            {"Engaged Solutions", "Declined"},
            {"eHealthCompare RA", "Declined"},
            {"eHealthCompare RA Sat", "Declined"},
            {"eHealthCompare RA Sun", "Declined"},
            {"eprospects", "Declined"},
            {"eprospect SAT", "Declined"},
            {"eprospect SUN", "Declined"},
            {"Esmart", "Declined"},
            {"Esmart Sat", "Declined"},
            {"Esmart Sun", "Declined"},
            {"finance_leads_online", "Declined"},
            {"50PlusLife.co.uk", "Declined"},
            {"Google", "Declined"},
            {"Hotkey(Internal)", "Declined"},
            {"HotKey Lead", "Declined"},
            {"Hotkey(Cavendish)", "Declined"},
            {"Hotkey(SunLife FLI)", "Declined"},
            {"Hotkey(SunLife GOF)", "Declined"},
            {"Impressia", "Declined"},
            {"internal", "Declined"},
            {"Kamicom", "Declined"},
            {"leadbay", "Declined"},
            {"LeadStream", "Declined"},
            {"LeadStream Sat", "Declined"},
            {"LeadStream Sun", "Declined"},
            {"Look For Health RA", "Declined"},
            {"Look For Health RA Sat", "Declined"},
            {"Look For Health RA Sun", "Declined"},
            {"look_for_life", "Declined"},
            {"Look For Life RA", "Declined"},
            {"Look For Life RA SAT", "Declined"},
            {"Look For Life RA SUN", "Declined"},
            {"LOANS REFERRAL", "Declined"},
            {"leadstream", "Declined"},
            {"leadstream Sat", "Declined"},
            {"leadstream Sun", "Declined"},
            {"livesure", "Declined"},
            {"Livesure RA", "Declined"},
            {"Livesure RA SAT", "Declined"},
            {"Livesure RA SUN", "Declined"},
            {"michael_anthony", "Declined"},
            {"michael_anthony SAT", "Declined"},
            {"michael_anthony SUN", "Declined"},
            {"michael_anthony ADD", "Declined"},
            {"MA WOL", "Declined"},
            {"MA WOL Sat", "Declined"},
            {"MA WOL Sun", "Declined"},
            {"MA WOL ADD", "Declined"},
            {"MA Switch", "Declined"},
            {"MA Switch Sat", "Declined"},
            {"MA Switch Sun", "Declined"},
            {"michael_anthony COMM", "Declined"},
            {"michael_anthony COMM SAT", "Declined"},
            {"michael_anthony COMM SUN", "Declined"},
            {"Baby Hotkey", "Declined"},
            {"Business Leads", "Declined"},
            {"BTQ Hotkey", "Declined"},
            {"BuyLife", "Declined"},
            {"First to Market", "Declined"},
            {"MA Inbound", "Declined"},
            {"Niche Data", "Declined"},
            {"Niche Hot Key", "Declined"},
            {"OSL", "Declined"},
            {"www.protected.co.uk", "Declined"},
            {"re-assured.co.uk", "Declined"},
            {"Customer Referral", "Declined"},
            {"SYN", "Declined"},
            {"melodi", "Declined"},
            {"Openwork", "Declined"},
            {"Protect4Life", "Declined"},
            {"premier_leads", "Declined"},
            {"premier_leads Sat", "Declined"},
            {"premier_leads Sun", "Declined"},
            {"PMI Advisor Callback", "Declined"},
            {"PMI Advisor Callback Sat", "Declined"},
            {"PMI Advisor Callback Sun", "Declined"},
            {"PMI Advisor Full Lead", "Declined"},
            {"PMI Advisor Full Lead Sat", "Declined"},
            {"PMI Advisor Full Lead Sun", "Declined"},
            {"PMI Pre CRM", "Declined"},
            {"Polly.co.uk", "Declined"},
            {"Polly.co.uk Sat", "Declined"},
            {"Polly.co.uk Sun", "Declined"},
            {"Provident", "Declined"},
            {"Quote Me Now", "Declined"},
            {"QSM Incentivised", "Declined"},
            {"QSM NotIncentivised", "Declined"},
            {"Quote Searcher", "Declined"},
            {"Quintessential", "Declined"},
            {"Quintessential Sat", "Declined"},
            {"Quintessential Sun", "Declined"},
            {"Reassured Archive S", "Declined"},
            {"Reassured Archive J", "Declined"},
            {"Reassured Health", "Declined"},
            {"Reassured Life", "Declined"},
            {"RA Email SurePolicy", "Declined"},
            {"RA Email SurePolicy SAT", "Declined"},
            {"RA Email SurePolicy SUN", "Declined"},
            {"RA PPC SureLoan", "Declined"},
            {"RA PPC SureLoan Sat", "Declined"},
            {"RA PPC SureLoan Sun", "Declined"},
            {"RA PPC SurePolicy", "Declined"},
            {"RA PPC SurePolicy SAT", "Declined"},
            {"RA PPC SurePolicy SUN", "Declined"},
            {"PMI Referral", "Declined"},
            {"PMI Client", "Declined"},
            {"Reassured Marketing", "Declined"},
            {"Reassured Marketing Sat", "Declined"},
            {"Reassured Marketing Sun", "Declined"},
            {"Reassured Marketing PMI", "Declined"},
            {"Reassured Marketing PMI SAT", "Declined"},
            {"Reassured Marketing PMI SUN", "Declined"},
            {"Reassured Marketing PPC", "Declined"},
            {"RA Shared Lead", "Declined"},
            {"RA Website", "Declined"},
            {"RA Website PMI", "Declined"},
            {"SunLife", "Declined"},
            {"SunLife Mature", "Declined"},
            {"SunLife Declined", "Declined"},
            {"SunLife - 45 day Expired", "Declined"},
            {"Sunlife GOF Capped", "Declined"},
            {"Sunlife GOF Capped DNC", "Declined"},
            {"Sunlife GOF", "Declined"},
            {"Sunlife GOF DNC", "Declined"},
            {"Sunlife GOF Customer Referral", "Declined"},
            {"Sunlife GOF(FLI)", "Declined"},
            {"Sunlife GOF (FLI) DNC", "Declined"},
            {"Sunlife GOF Expired", "Declined"},
            {"SunLife Hotkeys", "Declined"},
            {"SunLife Inbound", "Declined"},
            {"SunLife Customer Referral", "Declined"},
            {"Swinton Hotkeys", "Declined"},
            {"Trafix Media ", "Declined"},
            {"VeroCover", "Declined"},
            {"Visionary Markets", "Declined"},
            {"Visionary Markets Sat", "Declined"},
            {"Visionary Markets Sun", "Declined"},
            {"Visionary Markets Social", "Declined"},
            {"Apply Online", "Sold Incomplete"},
            {"Apply Online Sat", "Sold Incomplete"},
            {"Apply Online Sun", "Sold Incomplete"},
            {"Apply Online INCOMPLETE", "Sold Incomplete"},
            {"Apply Online INCOMPLETE Sat", "Sold Incomplete"},
            {"Apply Online INCOMPLETE Sun", "Sold Incomplete"},
            {"Aspect Webmedia", "Sold Incomplete"},
            {"Aspect Webmedia Sat", "Sold Incomplete"},
            {"Aspect Webmedia Sun", "Sold Incomplete"},
            {"Best Health Policy RA", "Sold Incomplete"},
            {"Best Health Policy RA Sat", "Sold Incomplete"},
            {"Best Health Policy RA Sun", "Sold Incomplete"},
            {"Cavendish", "Sold Incomplete"},
            {"Cavendish Dec", "Sold Incomplete"},
            {"Cavendish Dec - DNC", "Sold Incomplete"},
            {"Cavendish Dec - Hotkey", "Sold Incomplete"},
            {"Cavendish - DNC", "Sold Incomplete"},
            {"Cavendish Dec Customer Referral", "Sold Incomplete"},
            {"Cavendish - Hotkey", "Sold Incomplete"},
            {"Cavendish Customer Referral", "Sold Incomplete"},
            {"clixel", "Sold Incomplete"},
            {"CompareLife", "Sold Incomplete"},
            {"clixel RA", "Sold Incomplete"},
            {"Conectia", "Sold Incomplete"},
            {"Deal Direct FS", "Sold Incomplete"},
            {"DST Team", "Sold Incomplete"},
            {"Dove Insurance", "Sold Incomplete"},
            {"e-Finity", "Sold Incomplete"},
            {"Engaged Solutions", "Sold Incomplete"},
            {"eHealthCompare RA", "Sold Incomplete"},
            {"eHealthCompare RA Sat", "Sold Incomplete"},
            {"eHealthCompare RA Sun", "Sold Incomplete"},
            {"eprospects", "Sold Incomplete"},
            {"eprospect SAT", "Sold Incomplete"},
            {"eprospect SUN", "Sold Incomplete"},
            {"Esmart", "Sold Incomplete"},
            {"Esmart Sat", "Sold Incomplete"},
            {"Esmart Sun", "Sold Incomplete"},
            {"finance_leads_online", "Sold Incomplete"},
            {"50PlusLife.co.uk", "Sold Incomplete"},
            {"Google", "Sold Incomplete"},
            {"Hotkey(Internal)", "Sold Incomplete"},
            {"HotKey Lead", "Sold Incomplete"},
            {"Hotkey(Cavendish)", "Sold Incomplete"},
            {"Hotkey(SunLife FLI)", "Sold Incomplete"},
            {"Hotkey(SunLife GOF)", "Sold Incomplete"},
            {"Impressia", "Sold Incomplete"},
            {"internal", "Sold Incomplete"},
            {"Kamicom", "Sold Incomplete"},
            {"leadbay", "Sold Incomplete"},
            {"LeadStream", "Sold Incomplete"},
            {"LeadStream Sat", "Sold Incomplete"},
            {"LeadStream Sun", "Sold Incomplete"},
            {"Look For Health RA", "Sold Incomplete"},
            {"Look For Health RA Sat", "Sold Incomplete"},
            {"Look For Health RA Sun", "Sold Incomplete"},
            {"look_for_life", "Sold Incomplete"},
            {"Look For Life RA", "Sold Incomplete"},
            {"Look For Life RA SAT", "Sold Incomplete"},
            {"Look For Life RA SUN", "Sold Incomplete"},
            {"LOANS REFERRAL", "Sold Incomplete"},
            {"leadstream", "Sold Incomplete"},
            {"leadstream Sat", "Sold Incomplete"},
            {"leadstream Sun", "Sold Incomplete"},
            {"livesure", "Sold Incomplete"},
            {"Livesure RA", "Sold Incomplete"},
            {"Livesure RA SAT", "Sold Incomplete"},
            {"Livesure RA SUN", "Sold Incomplete"},
            {"michael_anthony", "Sold Incomplete"},
            {"michael_anthony SAT", "Sold Incomplete"},
            {"michael_anthony SUN", "Sold Incomplete"},
            {"michael_anthony ADD", "Sold Incomplete"},
            {"MA WOL", "Sold Incomplete"},
            {"MA WOL Sat", "Sold Incomplete"},
            {"MA WOL Sun", "Sold Incomplete"},
            {"MA WOL ADD", "Sold Incomplete"},
            {"MA Switch", "Sold Incomplete"},
            {"MA Switch Sat", "Sold Incomplete"},
            {"MA Switch Sun", "Sold Incomplete"},
            {"michael_anthony COMM", "Sold Incomplete"},
            {"michael_anthony COMM SAT", "Sold Incomplete"},
            {"michael_anthony COMM SUN", "Sold Incomplete"},
            {"Baby Hotkey", "Sold Incomplete"},
            {"Business Leads", "Sold Incomplete"},
            {"BTQ Hotkey", "Sold Incomplete"},
            {"BuyLife", "Sold Incomplete"},
            {"First to Market", "Sold Incomplete"},
            {"MA Inbound", "Sold Incomplete"},
            {"Niche Data", "Sold Incomplete"},
            {"Niche Hot Key", "Sold Incomplete"},
            {"OSL", "Sold Incomplete"},
            {"www.protected.co.uk", "Sold Incomplete"},
            {"re-assured.co.uk", "Sold Incomplete"},
            {"Customer Referral", "Sold Incomplete"},
            {"SYN", "Sold Incomplete"},
            {"melodi", "Sold Incomplete"},
            {"Openwork", "Sold Incomplete"},
            {"Protect4Life", "Sold Incomplete"},
            {"premier_leads", "Sold Incomplete"},
            {"premier_leads Sat", "Sold Incomplete"},
            {"premier_leads Sun", "Sold Incomplete"},
            {"PMI Advisor Callback", "Sold Incomplete"},
            {"PMI Advisor Callback Sat", "Sold Incomplete"},
            {"PMI Advisor Callback Sun", "Sold Incomplete"},
            {"PMI Advisor Full Lead", "Sold Incomplete"},
            {"PMI Advisor Full Lead Sat", "Sold Incomplete"},
            {"PMI Advisor Full Lead Sun", "Sold Incomplete"},
            {"PMI Pre CRM", "Sold Incomplete"},
            {"Polly.co.uk", "Sold Incomplete"},
            {"Polly.co.uk Sat", "Sold Incomplete"},
            {"Polly.co.uk Sun", "Sold Incomplete"},
            {"Provident", "Sold Incomplete"},
            {"Quote Me Now", "Sold Incomplete"},
            {"QSM Incentivised", "Sold Incomplete"},
            {"QSM NotIncentivised", "Sold Incomplete"},
            {"Quote Searcher", "Sold Incomplete"},
            {"Quintessential", "Sold Incomplete"},
            {"Quintessential Sat", "Sold Incomplete"},
            {"Quintessential Sun", "Sold Incomplete"},
            {"Reassured Archive S", "Sold Incomplete"},
            {"Reassured Archive J", "Sold Incomplete"},
            {"Reassured Health", "Sold Incomplete"},
            {"Reassured Life", "Sold Incomplete"},
            {"RA Email SurePolicy", "Sold Incomplete"},
            {"RA Email SurePolicy SAT", "Sold Incomplete"},
            {"RA Email SurePolicy SUN", "Sold Incomplete"},
            {"RA PPC SureLoan", "Sold Incomplete"},
            {"RA PPC SureLoan Sat", "Sold Incomplete"},
            {"RA PPC SureLoan Sun", "Sold Incomplete"},
            {"RA PPC SurePolicy", "Sold Incomplete"},
            {"RA PPC SurePolicy SAT", "Sold Incomplete"},
            {"RA PPC SurePolicy SUN", "Sold Incomplete"},
            {"PMI Referral", "Sold Incomplete"},
            {"PMI Client", "Sold Incomplete"},
            {"Reassured Marketing", "Sold Incomplete"},
            {"Reassured Marketing Sat", "Sold Incomplete"},
            {"Reassured Marketing Sun", "Sold Incomplete"},
            {"Reassured Marketing PMI", "Sold Incomplete"},
            {"Reassured Marketing PMI SAT", "Sold Incomplete"},
            {"Reassured Marketing PMI SUN", "Sold Incomplete"},
            {"Reassured Marketing PPC", "Sold Incomplete"},
            {"RA Shared Lead", "Sold Incomplete"},
            {"RA Website", "Sold Incomplete"},
            {"RA Website PMI", "Sold Incomplete"},
            {"SunLife", "Sold Incomplete"},
            {"SunLife Mature", "Sold Incomplete"},
            {"SunLife Sold Incomplete", "Sold Incomplete"},
            {"SunLife - 45 day Expired", "Sold Incomplete"},
            {"Sunlife GOF Capped", "Sold Incomplete"},
            {"Sunlife GOF Capped DNC", "Sold Incomplete"},
            {"Sunlife GOF", "Sold Incomplete"},
            {"Sunlife GOF DNC", "Sold Incomplete"},
            {"Sunlife GOF Customer Referral", "Sold Incomplete"},
            {"Sunlife GOF(FLI)", "Sold Incomplete"},
            {"Sunlife GOF (FLI) DNC", "Sold Incomplete"},
            {"Sunlife GOF Expired", "Sold Incomplete"},
            {"SunLife Hotkeys", "Sold Incomplete"},
            {"SunLife Inbound", "Sold Incomplete"},
            {"SunLife Customer Referral", "Sold Incomplete"},
            {"Swinton Hotkeys", "Sold Incomplete"},
            {"Trafix Media ", "Sold Incomplete"},
            {"VeroCover", "Sold Incomplete"},
            {"Visionary Markets", "Sold Incomplete"},
            {"Visionary Markets Sat", "Sold Incomplete"},
            {"Visionary Markets Sun", "Sold Incomplete"},
            {"Visionary Markets Social", "Sold Incomplete"},
            {"Apply Online", "Hot Key"},
            {"Apply Online Sat", "Hot Key"},
            {"Apply Online Sun", "Hot Key"},
            {"Apply Online INCOMPLETE", "Hot Key"},
            {"Apply Online INCOMPLETE Sat", "Hot Key"},
            {"Apply Online INCOMPLETE Sun", "Hot Key"},
            {"Aspect Webmedia", "Hot Key"},
            {"Aspect Webmedia Sat", "Hot Key"},
            {"Aspect Webmedia Sun", "Hot Key"},
            {"Best Health Policy RA", "Hot Key"},
            {"Best Health Policy RA Sat", "Hot Key"},
            {"Best Health Policy RA Sun", "Hot Key"},
            {"Cavendish", "Hot Key"},
            {"Cavendish Dec", "Hot Key"},
            {"Cavendish Dec - DNC", "Hot Key"},
            {"Cavendish Dec - Hotkey", "Hot Key"},
            {"Cavendish - DNC", "Hot Key"},
            {"Cavendish Dec Customer Referral", "Hot Key"},
            {"Cavendish - Hotkey", "Hot Key"},
            {"Cavendish Customer Referral", "Hot Key"},
            {"clixel", "Hot Key"},
            {"CompareLife", "Hot Key"},
            {"clixel RA", "Hot Key"},
            {"Conectia", "Hot Key"},
            {"Deal Direct FS", "Hot Key"},
            {"DST Team", "Hot Key"},
            {"Dove Insurance", "Hot Key"},
            {"e-Finity", "Hot Key"},
            {"Engaged Solutions", "Hot Key"},
            {"eHealthCompare RA", "Hot Key"},
            {"eHealthCompare RA Sat", "Hot Key"},
            {"eHealthCompare RA Sun", "Hot Key"},
            {"eprospects", "Hot Key"},
            {"eprospect SAT", "Hot Key"},
            {"eprospect SUN", "Hot Key"},
            {"Esmart", "Hot Key"},
            {"Esmart Sat", "Hot Key"},
            {"Esmart Sun", "Hot Key"},
            {"finance_leads_online", "Hot Key"},
            {"50PlusLife.co.uk", "Hot Key"},
            {"Google", "Hot Key"},
            {"Hotkey(Internal)", "Hot Key"},
            {"HotKey Lead", "Hot Key"},
            {"Hotkey(Cavendish)", "Hot Key"},
            {"Hotkey(SunLife FLI)", "Hot Key"},
            {"Hotkey(SunLife GOF)", "Hot Key"},
            {"Impressia", "Hot Key"},
            {"internal", "Hot Key"},
            {"Kamicom", "Hot Key"},
            {"leadbay", "Hot Key"},
            {"LeadStream", "Hot Key"},
            {"LeadStream Sat", "Hot Key"},
            {"LeadStream Sun", "Hot Key"},
            {"Look For Health RA", "Hot Key"},
            {"Look For Health RA Sat", "Hot Key"},
            {"Look For Health RA Sun", "Hot Key"},
            {"look_for_life", "Hot Key"},
            {"Look For Life RA", "Hot Key"},
            {"Look For Life RA SAT", "Hot Key"},
            {"Look For Life RA SUN", "Hot Key"},
            {"LOANS REFERRAL", "Hot Key"},
            {"leadstream", "Hot Key"},
            {"leadstream Sat", "Hot Key"},
            {"leadstream Sun", "Hot Key"},
            {"livesure", "Hot Key"},
            {"Livesure RA", "Hot Key"},
            {"Livesure RA SAT", "Hot Key"},
            {"Livesure RA SUN", "Hot Key"},
            {"michael_anthony", "Hot Key"},
            {"michael_anthony SAT", "Hot Key"},
            {"michael_anthony SUN", "Hot Key"},
            {"michael_anthony ADD", "Hot Key"},
            {"MA WOL", "Hot Key"},
            {"MA WOL Sat", "Hot Key"},
            {"MA WOL Sun", "Hot Key"},
            {"MA WOL ADD", "Hot Key"},
            {"MA Switch", "Hot Key"},
            {"MA Switch Sat", "Hot Key"},
            {"MA Switch Sun", "Hot Key"},
            {"michael_anthony COMM", "Hot Key"},
            {"michael_anthony COMM SAT", "Hot Key"},
            {"michael_anthony COMM SUN", "Hot Key"},
            {"Baby Hotkey", "Hot Key"},
            {"Business Leads", "Hot Key"},
            {"BTQ Hotkey", "Hot Key"},
            {"BuyLife", "Hot Key"},
            {"First to Market", "Hot Key"},
            {"MA Inbound", "Hot Key"},
            {"Niche Data", "Hot Key"},
            {"Niche Hot Key", "Hot Key"},
            {"OSL", "Hot Key"},
            {"www.protected.co.uk", "Hot Key"},
            {"re-assured.co.uk", "Hot Key"},
            {"Customer Referral", "Hot Key"},
            {"SYN", "Hot Key"},
            {"melodi", "Hot Key"},
            {"Openwork", "Hot Key"},
            {"Protect4Life", "Hot Key"},
            {"premier_leads", "Hot Key"},
            {"premier_leads Sat", "Hot Key"},
            {"premier_leads Sun", "Hot Key"},
            {"PMI Advisor Callback", "Hot Key"},
            {"PMI Advisor Callback Sat", "Hot Key"},
            {"PMI Advisor Callback Sun", "Hot Key"},
            {"PMI Advisor Full Lead", "Hot Key"},
            {"PMI Advisor Full Lead Sat", "Hot Key"},
            {"PMI Advisor Full Lead Sun", "Hot Key"},
            {"PMI Pre CRM", "Hot Key"},
            {"Polly.co.uk", "Hot Key"},
            {"Polly.co.uk Sat", "Hot Key"},
            {"Polly.co.uk Sun", "Hot Key"},
            {"Provident", "Hot Key"},
            {"Quote Me Now", "Hot Key"},
            {"QSM Incentivised", "Hot Key"},
            {"QSM NotIncentivised", "Hot Key"},
            {"Quote Searcher", "Hot Key"},
            {"Quintessential", "Hot Key"},
            {"Quintessential Sat", "Hot Key"},
            {"Quintessential Sun", "Hot Key"},
            {"Reassured Archive S", "Hot Key"},
            {"Reassured Archive J", "Hot Key"},
            {"Reassured Health", "Hot Key"},
            {"Reassured Life", "Hot Key"},
            {"RA Email SurePolicy", "Hot Key"},
            {"RA Email SurePolicy SAT", "Hot Key"},
            {"RA Email SurePolicy SUN", "Hot Key"},
            {"RA PPC SureLoan", "Hot Key"},
            {"RA PPC SureLoan Sat", "Hot Key"},
            {"RA PPC SureLoan Sun", "Hot Key"},
            {"RA PPC SurePolicy", "Hot Key"},
            {"RA PPC SurePolicy SAT", "Hot Key"},
            {"RA PPC SurePolicy SUN", "Hot Key"},
            {"PMI Referral", "Hot Key"},
            {"PMI Client", "Hot Key"},
            {"Reassured Marketing", "Hot Key"},
            {"Reassured Marketing Sat", "Hot Key"},
            {"Reassured Marketing Sun", "Hot Key"},
            {"Reassured Marketing PMI", "Hot Key"},
            {"Reassured Marketing PMI SAT", "Hot Key"},
            {"Reassured Marketing PMI SUN", "Hot Key"},
            {"Reassured Marketing PPC", "Hot Key"},
            {"RA Shared Lead", "Hot Key"},
            {"RA Website", "Hot Key"},
            {"RA Website PMI", "Hot Key"},
            {"SunLife", "Hot Key"},
            {"SunLife Mature", "Hot Key"},
            {"SunLife Sold Incomplete", "Hot Key"},
            {"SunLife - 45 day Expired", "Hot Key"},
            {"Sunlife GOF Capped", "Hot Key"},
            {"Sunlife GOF Capped DNC", "Hot Key"},
            {"Sunlife GOF", "Hot Key"},
            {"Sunlife GOF DNC", "Hot Key"},
            {"Sunlife GOF Customer Referral", "Hot Key"},
            {"Sunlife GOF(FLI)", "Hot Key"},
            {"Sunlife GOF (FLI) DNC", "Hot Key"},
            {"Sunlife GOF Expired", "Hot Key"},
            {"SunLife Hotkeys", "Hot Key"},
            {"SunLife Inbound", "Hot Key"},
            {"SunLife Customer Referral", "Hot Key"},
            {"Swinton Hotkeys", "Hot Key"},
            {"Trafix Media ", "Hot Key"},
            {"VeroCover", "Hot Key"},
            {"Visionary Markets", "Hot Key"},
            {"Visionary Markets Sat", "Hot Key"},
            {"Visionary Markets Sun", "Hot Key"},
            {"Visionary Markets Social", "Hot Key"}
    };
}
