package TestPrep;

/**
 * Created by hfletcher on 19/06/2018.
 */
public class PNLeadProvidersAndStatusesOne {

    public static String[][] PNLeadProvidersAndStatuses = new String[][]{
            {"michael_anthony", "Not Contacted"},
            {"look_for_life", "Not Contacted"},
            {"livesure", "Not Contacted"},
            {"michael_anthony SAT", "Not Contacted"},
            {"michael_anthony SUN", "Not Contacted"},
            {"Look For Life RA", "Not Contacted"},
            {"Livesure RA", "Not Contacted"},
            {"Look For Life RA SAT", "Not Contacted"},
            {"Look For Life RA SUN", "Not Contacted"},
            {"premier_leads Sat", "Not Contacted"},
            {"premier_leads Sun", "Not Contacted"},
            {"Quintessential", "Not Contacted"},
            {"michael_anthony ADD", "Not Contacted"},
            {"e-Finity", "Not Contacted"},
            {"Visionary Markets", "Not Contacted"},
            {"MA WOL", "Not Contacted"},
            {"MA WOL Sat", "Not Contacted"},
            {"MA WOL Sun", "Not Contacted"},
            {"MA WOL ADD", "Not Contacted"},
            {"LeadStream", "Not Contacted"},
            {"LeadStream Sat", "Not Contacted"},
            {"LeadStream Sun", "Not Contacted"},
            {"Quintessential Sat", "Not Contacted"},
            {"Quintessential Sun", "Not Contacted"},
            {"leadstream", "Not Contacted"},
            {"leadstream Sat", "Not Contacted"},
            {"leadstream Sun", "Not Contacted"},
            {"VeroCover", "Not Contacted"},
            {"Impressia", "Not Contacted"},
            {"MA Switch", "Not Contacted"},
            {"MA Switch Sat", "Not Contacted"},
            {"MA Switch Sun", "Not Contacted"},
            {"Conectia", "Not Contacted"},
            {"Quote Me Now", "Not Contacted"},
            {"michael_anthony COMM", "Not Contacted"},
            {"Visionary Markets Sat", "Not Contacted"},
            {"Visionary Markets Sun", "Not Contacted"},
            {"michael_anthony COMM SAT", "Not Contacted"},
            {"michael_anthony COMM SUN", "Not Contacted"},
            {"Kamicom", "Not Contacted"},
            {"Trafix Media", "Not Contacted"},
            {"Visionary Markets Social", "Not Contacted"},
            {"Polly.co.uk", "Not Contacted"},
            {"Polly.co.uk Sat", "Not Contacted"},
            {"Polly.co.uk Sun", "Not Contacted"},
            {"DMLS", "Not Contacted"},
            {"DMLS Sat", "Not Contacted"},
            {"DMLS Sun", "Not Contacted"},
            {"michael_anthony", "Contacted"},
            {"look_for_life", "Contacted"},
            {"livesure", "Contacted"},
            {"michael_anthony SAT", "Contacted"},
            {"michael_anthony SUN", "Contacted"},
            {"Look For Life RA", "Contacted"},
            {"Livesure RA", "Contacted"},
            {"Look For Life RA SAT", "Contacted"},
            {"Look For Life RA SUN", "Contacted"},
            {"premier_leads Sat", "Contacted"},
            {"premier_leads Sun", "Contacted"},
            {"Quintessential", "Contacted"},
            {"michael_anthony ADD", "Contacted"},
            {"e-Finity", "Contacted"},
            {"Visionary Markets", "Contacted"},
            {"MA WOL", "Contacted"},
            {"MA WOL Sat", "Contacted"},
            {"MA WOL Sun", "Contacted"},
            {"MA WOL ADD", "Contacted"},
            {"LeadStream", "Contacted"},
            {"LeadStream Sat", "Contacted"},
            {"LeadStream Sun", "Contacted"},
            {"Quintessential Sat", "Contacted"},
            {"Quintessential Sun", "Contacted"},
            {"leadstream", "Contacted"},
            {"leadstream Sat", "Contacted"},
            {"leadstream Sun", "Contacted"},
            {"VeroCover", "Contacted"},
            {"Impressia", "Contacted"},
            {"MA Switch", "Contacted"},
            {"MA Switch Sat", "Contacted"},
            {"MA Switch Sun", "Contacted"},
            {"Conectia", "Contacted"},
            {"Quote Me Now", "Contacted"},
            {"michael_anthony COMM", "Contacted"},
            {"Visionary Markets Sat", "Contacted"},
            {"Visionary Markets Sun", "Contacted"},
            {"michael_anthony COMM SAT", "Contacted"},
            {"michael_anthony COMM SUN", "Contacted"},
            {"Kamicom", "Contacted"},
            {"Trafix Media", "Contacted"},
            {"Visionary Markets Social", "Contacted"},
            {"Polly.co.uk", "Contacted"},
            {"Polly.co.uk Sat", "Contacted"},
            {"Polly.co.uk Sun", "Contacted"},
            {"DMLS", "Contacted"},
            {"DMLS Sat", "Contacted"},
            {"DMLS Sun", "Contacted"},
            {"michael_anthony", "New"},
            {"look_for_life", "New"},
            {"livesure", "New"},
            {"michael_anthony SAT", "New"},
            {"michael_anthony SUN", "New"},
            {"Look For Life RA", "New"},
            {"Livesure RA", "New"},
            {"Look For Life RA SAT", "New"},
            {"Look For Life RA SUN", "New"},
            {"premier_leads Sat", "New"},
            {"premier_leads Sun", "New"},
            {"Quintessential", "New"},
            {"michael_anthony ADD", "New"},
            {"e-Finity", "New"},
            {"Visionary Markets", "New"},
            {"MA WOL", "New"},
            {"MA WOL Sat", "New"},
            {"MA WOL Sun", "New"},
            {"MA WOL ADD", "New"},
            {"LeadStream", "New"},
            {"LeadStream Sat", "New"},
            {"LeadStream Sun", "New"},
            {"Quintessential Sat", "New"},
            {"Quintessential Sun", "New"},
            {"leadstream", "New"},
            {"leadstream Sat", "New"},
            {"leadstream Sun", "New"},
            {"VeroCover", "New"},
            {"Impressia", "New"},
            {"MA Switch", "New"},
            {"MA Switch Sat", "New"},
            {"MA Switch Sun", "New"},
            {"Conectia", "New"},
            {"Quote Me Now", "New"},
            {"michael_anthony COMM", "New"},
            {"Visionary Markets Sat", "New"},
            {"Visionary Markets Sun", "New"},
            {"michael_anthony COMM SAT", "New"},
            {"michael_anthony COMM SUN", "New"},
            {"Kamicom", "New"},
            {"Trafix Media", "New"},
            {"Visionary Markets Social", "New"},
            {"Polly.co.uk", "New"},
            {"Polly.co.uk Sat", "New"},
            {"Polly.co.uk Sun", "New"},
            {"DMLS", "New"},
            {"DMLS Sat", "New"},
            {"DMLS Sun", "New"}

    };

}
