package CreateLeadsEveryProvider;

/**
 * Created by hfletcher on 21/06/2018.
 */
public class LeadProviders {

    //These are the lead providers that SHOULD receive a privacy notice
    public static String[] leadProvidersListOne = new String[]{
            "finance_leads_online",
            "premier_leads",
            "clixel",
            "michael_anthony",
            "melodi",
            "eprospects",
            "leadbay",
            "look_for_life",
            "livesure",
            "michael_anthony SAT",
            "michael_anthony SUN",
            "Baby Hotkey",
            "BTQ Hotkey",
            "MA Inbound",
            "www.protected.co.uk",
            "Niche Data",
            "Niche Hot Key",
            "First to Market",
            "BuyLife",
            "eprospect SAT",
            "eprospect SUN",
            "clixel RA",
            "Look For Life RA",
            "Livesure RA",
            "Look For Life RA SAT",
            "Look For Life RA SUN",
            "Livesure RA SAT",
            "Livesure RA SUN",
            "CompareLife",
            "Look For Health RA",
            "Look For Health RA Sat",
            "Look For Health RA Sun",
            "eHealthCompare RA",
            "eHealthCompare RA Sat",
            "eHealthCompare RA Sun",
            "Best Health Policy RA",
            "Best Health Policy RA Sat",
            "Best Health Policy RA Sun",
            "premier_leads Sat",
            "premier_leads Sun",
            "50PlusLife.co.uk",
            "Esmart",
            "Esmart Sat",
            "Esmart Sun",
            "Engaged Solutions",
            "Aspect Webmedia",
            "Quintessential",
            "Protect4Life",
            "LOANS REFERRAL",
            "michael_anthony ADD",
            "e-Finity",
            "Visionary Markets",
            "Dove Insurance",
            "QSM Incentivised",
            "QSM NotIncentivised",
            "MA WOL",
            "MA WOL Sat",
            "MA WOL Sun",
            "MA WOL ADD",
            "Aspect Webmedia Sat",
            "Aspect Webmedia Sun",
            "LeadStream",
            "LeadStream Sat",
            "LeadStream Sun",
            "Quintessential Sat",
            "Quintessential Sun",
            "leadstream",
            "leadstream Sat",
            "leadstream Sun",
            "VeroCover",
            "Impressia",
            "MA Switch",
            "MA Switch Sat",
            "MA Switch Sun",
            "Conectia",
            "Quote Me Now",
            "Quote Searcher",
            "michael_anthony COMM",
            "Visionary Markets Sat",
            "Visionary Markets Sun",
            "michael_anthony COMM SAT",
            "michael_anthony COMM SUN",
            "Kamicom",
            "Trafix Media ",
            "Visionary Markets Social",
            "Polly.co.uk",
            "Polly.co.uk Sat",
            "Polly.co.uk Sun",
            "DMLS",
            "DMLS Sat",
            "DMLS Sun"
    };

    //These are the lead providers that SHOULD NOT receive a privacy notice
    public static String[] leadProvidersListTwo = new String[]{
            "SYN",
            //"Swinton Hotkeys", //This lead provider requires a reference, which the script doesn't have, so it's been left out.
            "SunLife Mature",
            "SunLife Inbound",
            "SunLife Hotkeys",
            "Sunlife GOF(FLI)",
            "Sunlife GOF Expired",
            "Sunlife GOF DNC",
            "Sunlife GOF Customer Referral",
            "Sunlife GOF Capped DNC",
            "Sunlife GOF Capped",
            "Sunlife GOF (FLI) DNC",
            "Sunlife GOF",
            "SunLife Declined",
            "SunLife Customer Referral",
            "SunLife - 45 day Expired",
            "SunLife",
            "Reassured Marketing Sun",
            "Reassured Marketing Sat",
            "Reassured Marketing PPC",
            "Reassured Marketing PMI SUN",
            "Reassured Marketing PMI SAT",
            "Reassured Marketing PMI",
            "Reassured Marketing",
            "Reassured Life",
            "Reassured Health",
            "Reassured Archive S",
            "Reassured Archive J",
            "re-assured.co.uk",
            "RA Website PMI",
            "RA Website",
            "RA Shared Lead",
            "RA PPC SurePolicy SUN",
            "RA PPC SurePolicy SAT",
            "RA PPC SurePolicy",
            "RA PPC SureLoan Sun",
            "RA PPC SureLoan Sat",
            "RA PPC SureLoan",
            "RA Email SurePolicy SUN",
            "RA Email SurePolicy SAT",
            "RA Email SurePolicy",
            "Provident",
            "PMI Referral",
            "PMI Pre CRM",
            "PMI Client",
            "PMI Advisor Full Lead Sun",
            "PMI Advisor Full Lead Sat",
            "PMI Advisor Full Lead",
            "PMI Advisor Callback Sun",
            "PMI Advisor Callback Sat",
            "PMI Advisor Callback",
            "OSL",
            "Openwork",
            "internal",
            "Hotkey(SunLife GOF)",
            "Hotkey(SunLife FLI)",
            "Hotkey(Internal)",
            "Hotkey(Cavendish)",
            "HotKey Lead",
            "Google",
            "DST Team",
            "Deal Direct FS",
            "Customer Referral",
            "Cavendish Dec Customer Referral",
            "Cavendish Dec - Hotkey",
            "Cavendish Dec - DNC",
            "Cavendish Dec",
            "Cavendish Customer Referral",
            "Cavendish - Hotkey",
            "Cavendish - DNC",
            "Cavendish",
            "Business Leads",
            "Apply Online Sun",
            "Apply Online Sat",
            "Apply Online INCOMPLETE Sun",
            "Apply Online INCOMPLETE Sat",
            "Apply Online INCOMPLETE",
            "Apply Online"
    };
}
